### PR TITLE
Enable spotless

### PR DESCRIPTION
**Pull request by Vlatombe**
Because too much style

To format existing code, run:

```
mvn spotless:apply
```

### Testing done

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by jglick** [comment]
Flake?

```
org.awaitility.core.ConditionTimeoutException: org.csanchez.jenkins.plugins.kubernetes.pipeline.KubernetesPipelineTest expected a collection with size <1> but collection size was <2> within 10 seconds.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.awaitility.core.AbstractHamcrestCondition.await(AbstractHamcrestCondition.java:86)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:691)
	at org.csanchez.jenkins.plugins.kubernetes.pipeline.KubernetesPipelineTest.dynamicPVCVolume(KubernetesPipelineTest.java:771)
```

**Comment by Vlatombe** [comment]
Partly split to #1480

**Comment by jglick** [comment]
Remember to add 9c1d58d9badd988622b4772632037126176e1ef0 to the ignore list for blame.

**Comment by Vlatombe** [comment]
Done in 808c05ac2ce6d53fdd31d70e01b7287a8f6d3ff3

**Pull request merged**
