### PR TITLE
Allow option `showRawYaml` in Jenkinsfiles

### PR DESCRIPTION
**Pull request by OliverNocon**
Add option to hide pod yaml also in Jenkinsfile pipeline execution by setting `showRawYaml: false`.

https://issues.jenkins-ci.org/browse/JENKINS-57717

### CODE REVIEW

**Comment by OliverNocon** [comment]
Change has been successfully tested e2e in Jenkins instance running in a Kubernetes cluster.

**Comment by Vlatombe** [comment]
Thanks for this. Would you mind adding a small unit test ?

**Comment by OliverNocon** [comment]
sure, could you please point me to the place where I can find the test for the non-pipeline use-case. I will then take this over.

**Comment by Vlatombe** [comment]
See https://github.com/jenkinsci/kubernetes-plugin/blob/master/src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateTest.java

**Comment by OliverNocon** [comment]
Thanks for the pointer. I added a simple Unit test now. 
Involving `ContainerTemplate` does not look feasible to me here.

I looked into testing the additions to class `PodTemplateStepExecution`.
Unfortunately, a more detailed but simple unit test for this class does not look as easy to me without refactoring the class itself since the constructor does not set the properties but rather the `start()` method which already requires `Jenkins.getInstance()`.
I don't want to go into refactoring here though.

Hope this is fine ...

**Comment by Vlatombe** [comment]
This unit test is not really useful (merely testing the getter). Usually anything involving something related to pipeline steps is better tested using an integration test.

**Comment by OliverNocon** [comment]
I fully agree that testing getters and setters is not of much value.
I would have wished for a better unit test capability of PodTemplateStepExecution in a way that I could just run the `start()` method on `PodTemplateStep` and then assert that the correct value made it into `newTemplate`.
That could make testing faster in my opinion and easier for new contributors ...

Anyway, thank you for your hint.
Since I cannot run the tests locally I gave it a try with an integration test and a best guess now ...

**Comment by OliverNocon** [comment]
@Vlatombe thanks for helping out here!

**Pull request merged**
