### PR TITLE
[JENKINS-51273] sshAgent fails on declarative pipeline and also yaml

### PR DESCRIPTION
**Pull request by carlossg**
[JENKINS-51273](https://issues.jenkins-ci.org/browse/JENKINS-51273) by @MattLud 

Change-Id: I62c82b61f81e74fe31d8d961fe4cb3c099a354c6

### CODE REVIEW

**Comment by Vlatombe** [comment]
`ssh-agent` creates the socket file under `/tmp`, which is not inside the workspace volume so it isn't shared between the different containers of the same pod. Unfortunately socket files length is limited to 108 chars so it is not possible to create it under the workspace volume.
I've tried, with some success, to add an empty dir volume to the pod definition and mount it in `/tmp` so that it is shared between containers, and it seems to do the trick. In declarative however, it is not possible to declare volumes without using yaml attribute.

The kubernetes plugin may go the extra step of mounting `/tmp` (maybe with a toggle switch so that it can be disabled in case of problem) to make this kind of use case easier to deal with.

**Comment by Vlatombe** [comment]
https://github.com/MattLud/kubernetes-plugin/pull/1

**Comment by jglick** [comment]
Workspace volumes in Kubernetes agents are preset paths so keeping them to 108 characters should be easy.

Rather than mounting `/tmp` we could define `$TEMP` for build steps to be the `...@tmp` dir which is already mounted and shared between containers. I have been thinking about doing this for the `node` step generally anyway.

**Comment by Vlatombe** [comment]
Stale

**Comment by jglick** [comment]
I guess this is after https://github.com/jenkinsci/ssh-agent-plugin/pull/18?

I think you should just not attempt to mix `sshagent` and `container`. More straightforward to use `withCredentials` to bind a private key to a local file and then pass it as, say, a `-i` argument to some command.

**Comment by MattLud** [comment]
Way back in 2018 when I opened this, the plugin was in a much different state where the plugin didn't have feature parity with non-pod build agents. As a result, this ticket may no longer be relevant but I can double check it.

**Pull request closed without merging**
