### PR TITLE
showRawYaml default value changed to false

### PR DESCRIPTION
**Pull request by PierluigiLenociAkelius**
Changing the default behaviour of the plugin in this way make no sense for me.
Inside yaml file could be saved secret or other sensitive data.

### CODE REVIEW

**Comment by jglick** [comment]
> Inside yaml file could be saved secret or other sensitive data.

Normally this would be handled using Kubernetes `Secret`s. (Or, if you are using `podTemplate` and wish to bind something from Jenkins credentials, the `withCredentials` step will automatically mask out the actual value.)

**Comment by Vlatombe** [comment]
I agree with Jesse. A possible improvement would be to manage this globally using a flag in the KubernetesCloud global configuration, if you want to disable it for all your pod templates without going through the trouble of setting it in your Jenkinsfiles.

**Comment by pakoAku** [comment]
Hey guys,

just to say this plugin is really great and I happy to see the constant improvements.

We would be very happy if you could create such global switch as we are more concerned about the Jenkins Agent secret.

See below a snippet of the printed Pod definition (I removed a lot of parts but I think you got the point)
`
    containers:
    - command:
      - "cat"
      env:
      - name: "JENKINS_SECRET"
        value: "the secret value"`

**Comment by Vlatombe** [comment]
This is a fair ask. These values could be redacted instead.

Le ven. 19 juil. 2019 à 09:29, Patrick Kolze <notifications@github.com> a
écrit :

**Comment by Vlatombe** [comment]
I filed #552 to address the `JENKINS_SECRET`.

**Comment by Vlatombe** [comment]
The JENKINS_SECRET is now hidden, and I filed #556 to fix inheritance of `showRawYaml`, so you can just set it to false in the pod template referenced in "Defaults Provider Template Name".

**Pull request closed without merging**
