### PR TITLE
[JENKINS-61409] DEFAULT_JNLP_IMAGE update for 2.222.4

### PR DESCRIPTION
**Pull request by jglick**
Amending https://github.com/jenkinsci/kubernetes-plugin/pull/661 to pick up https://github.com/jenkinsci/docker-jnlp-slave/pull/153.

### CODE REVIEW

**Comment by Vlatombe** [comment]
Core version should be bumped to to new 2.222.x avoid any inconsistency.

**Comment by jglick** [comment]
Also `src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/samples/windows.groovy` is currently using `jenkins/jnlp-agent:latest-windows` which will need to be updated I guess as in #753, though I am not sure to what (there is [no `latest-windows` tag](https://hub.docker.com/r/jenkins/inbound-agent/tags)). CC @slide

**Comment by slide** [comment]
`jenkins/inbound-agent:windowsservercore-1809` should be used, using manifests is on the list of things so that we can get just a `:latest`

**Comment by JRemitz** [comment]
With LTS version [`2.222.4`](https://jenkins.io/changelog-stable//#v2.222.4) they have now upgraded remoting to v4.

> _Bug:Upgrade to Remoting 4.2.1 to fix an issue with large payloads over WebSockets.Requires a matching agent.jar with remoting 4.2.1 or later._

We patched yesterday and we couldn't get k8s slaves running unless we were using the `jenkins/inbound-agent:latest` or that matched the above version. `jenkins/jnlp-slave:latest` current build does not work with it that we could identify.

I think now is a good time to get this updated, but i assume it is a breaking change and requires Jenkins `2.222.4+` if you're using web sockets.

**Comment by jglick** [comment]
Yes, I plan to change the baseline version here and put this up for review shortly. We were waiting for 2.222.4 to ship (was accidentally delayed).

**Pull request merged**
