### PR TITLE
Set offline cause when Pod is terminated

### PR DESCRIPTION
**Pull request by cronik**
When the Reaper terminates a slave node on Pod failure events set the offline cause to improve feedback when builds fail.

Calling `Computer#disconnect` after `KubernetesSlave#terminate()` or `Jenkings#removeNode()` is a bit redundant. Both methods eventually call `Nodes#removeNode` which will call `Computer#disconnect` and set a generic "node removed" message. But calling disconnect again with our more specific cause any build failures will report a more detailed message in the console log.

> org.jenkinsci.plugins.workflow.support.steps.AgentOfflineException: Unable to create live FilePath for example-agent-n74z5; example-agent-n74z5 was marked offline: Pod failed (Reason: Evicted, Message: Pod ephemeral local storage usage exceeds the total limit of containers 4Gi. )

The ultimate goal here is to give better feedback in build logs when a build fails due to Pod failure. I explored a number of different approaches of reporting Pod status messages to the BuildListener but this was the best I could find. If there is a better way I'd be happy to give it a shot.

The one down side to calling `terminate()` and `disconnect()` is `Computer#recordTermination()` is called multiple times, so some error reporting can get very verbose. `recordTermination()` is called 3x during `KubernetesSlave#terminate()` (this seems like a potential bug?) and 1x during `Computer#disconnect()`, so only 1 extra termination request is added to the list.

<details>
  <summary>Example Termination Request Stack Trace</summary>
<pre>
Also:   hudson.model.Computer$TerminationRequest: Termination requested at Mon Apr 03 15:38:33 EDT 2023 by Thread[OkHttp https://127.0.0.1/...,5,main] [id=248]
		at hudson.model.Computer.recordTermination(Computer.java:237)
		at hudson.slaves.AbstractCloudSlave.terminate(AbstractCloudSlave.java:85)
		at org.csanchez.jenkins.plugins.kubernetes.pod.retention.Reaper.logLastLinesThenTerminateNode(Reaper.java:481)
		at org.csanchez.jenkins.plugins.kubernetes.pod.retention.Reaper$TerminateAgentOnPodFailed.onEvent(Reaper.java:459)
		at org.csanchez.jenkins.plugins.kubernetes.pod.retention.Reaper$CloudPodWatcher.lambda$eventReceived$0(Reaper.java:322)
		at jenkins.util.Listeners.lambda$notify$0(Listeners.java:59)
		at jenkins.util.Listeners.notify(Listeners.java:67)
		at org.csanchez.jenkins.plugins.kubernetes.pod.retention.Reaper$CloudPodWatcher.eventReceived(Reaper.java:320)
		at org.csanchez.jenkins.plugins.kubernetes.pod.retention.Reaper$CloudPodWatcher.eventReceived(Reaper.java:280)
		at io.fabric8.kubernetes.client.utils.internal.WatcherToggle.eventReceived(WatcherToggle.java:49)
		at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.eventReceived(AbstractWatchManager.java:191)
		at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.onMessage(AbstractWatchManager.java:268)
		at io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener.onMessage(WatcherWebSocketListener.java:55)
		at io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl$1.onMessage(OkHttpWebSocketImpl.java:117)
		at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:333)
		at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:245)
		at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:106)
		at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
		at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
		at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
Also:   hudson.model.Computer$TerminationRequest: Termination requested at Mon Apr 03 15:38:33 EDT 2023 by Thread[OkHttp https://127.0.0.1/...,5,main] [id=248]
		at hudson.model.Computer.recordTermination(Computer.java:237)
		at jenkins.model.Nodes$5.run(Nodes.java:275)
		at hudson.model.Queue._withLock(Queue.java:1395)
		at hudson.model.Queue.withLock(Queue.java:1269)
		at jenkins.model.Nodes.removeNode(Nodes.java:270)
		at jenkins.model.Jenkins.removeNode(Jenkins.java:2228)
		at hudson.slaves.AbstractCloudSlave.terminate(AbstractCloudSlave.java:91)
		at org.csanchez.jenkins.plugins.kubernetes.pod.retention.Reaper.logLastLinesThenTerminateNode(Reaper.java:481)
		at org.csanchez.jenkins.plugins.kubernetes.pod.retention.Reaper$TerminateAgentOnPodFailed.onEvent(Reaper.java:459)
		at org.csanchez.jenkins.plugins.kubernetes.pod.retention.Reaper$CloudPodWatcher.lambda$eventReceived$0(Reaper.java:322)
		at jenkins.util.Listeners.lambda$notify$0(Listeners.java:59)
		at jenkins.util.Listeners.notify(Listeners.java:67)
		at org.csanchez.jenkins.plugins.kubernetes.pod.retention.Reaper$CloudPodWatcher.eventReceived(Reaper.java:320)
		at org.csanchez.jenkins.plugins.kubernetes.pod.retention.Reaper$CloudPodWatcher.eventReceived(Reaper.java:280)
		at io.fabric8.kubernetes.client.utils.internal.WatcherToggle.eventReceived(WatcherToggle.java:49)
		at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.eventReceived(AbstractWatchManager.java:191)
		at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.onMessage(AbstractWatchManager.java:268)
		at io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener.onMessage(WatcherWebSocketListener.java:55)
		at io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl$1.onMessage(OkHttpWebSocketImpl.java:117)
		at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:333)
		at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:245)
		at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:106)
		at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
		at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
		at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
Also:   hudson.model.Computer$TerminationRequest: Termination requested at Mon Apr 03 15:38:33 EDT 2023 by Thread[OkHttp https://127.0.0.1/...,5,main] [id=248]
		at hudson.model.Computer.recordTermination(Computer.java:237)
		at hudson.model.Computer.disconnect(Computer.java:507)
		at hudson.slaves.SlaveComputer.disconnect(SlaveComputer.java:813)
		at jenkins.model.Nodes$5.run(Nodes.java:276)
		at hudson.model.Queue._withLock(Queue.java:1395)
		at hudson.model.Queue.withLock(Queue.java:1269)
		at jenkins.model.Nodes.removeNode(Nodes.java:270)
		at jenkins.model.Jenkins.removeNode(Jenkins.java:2228)
		at hudson.slaves.AbstractCloudSlave.terminate(AbstractCloudSlave.java:91)
		at org.csanchez.jenkins.plugins.kubernetes.pod.retention.Reaper.logLastLinesThenTerminateNode(Reaper.java:481)
		at org.csanchez.jenkins.plugins.kubernetes.pod.retention.Reaper$TerminateAgentOnPodFailed.onEvent(Reaper.java:459)
		at org.csanchez.jenkins.plugins.kubernetes.pod.retention.Reaper$CloudPodWatcher.lambda$eventReceived$0(Reaper.java:322)
		at jenkins.util.Listeners.lambda$notify$0(Listeners.java:59)
		at jenkins.util.Listeners.notify(Listeners.java:67)
		at org.csanchez.jenkins.plugins.kubernetes.pod.retention.Reaper$CloudPodWatcher.eventReceived(Reaper.java:320)
		at org.csanchez.jenkins.plugins.kubernetes.pod.retention.Reaper$CloudPodWatcher.eventReceived(Reaper.java:280)
		at io.fabric8.kubernetes.client.utils.internal.WatcherToggle.eventReceived(WatcherToggle.java:49)
		at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.eventReceived(AbstractWatchManager.java:191)
		at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.onMessage(AbstractWatchManager.java:268)
		at io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener.onMessage(WatcherWebSocketListener.java:55)
		at io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl$1.onMessage(OkHttpWebSocketImpl.java:117)
		at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:333)
		at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:245)
		at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:106)
		at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
		at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
		at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
Also:   hudson.model.Computer$TerminationRequest: Termination requested at Mon Apr 03 15:38:33 EDT 2023 by Thread[OkHttp https://100.114.0.1/...,5,main] [id=248]
		at hudson.model.Computer.recordTermination(Computer.java:237)
		at hudson.model.Computer.disconnect(Computer.java:507)
		at hudson.slaves.SlaveComputer.disconnect(SlaveComputer.java:813)
		at org.csanchez.jenkins.plugins.kubernetes.pod.retention.Reaper.disconnectComputer(Reaper.java:468)
		at org.csanchez.jenkins.plugins.kubernetes.pod.retention.Reaper$TerminateAgentOnPodFailed.onEvent(Reaper.java:460)
		at org.csanchez.jenkins.plugins.kubernetes.pod.retention.Reaper$CloudPodWatcher.lambda$eventReceived$0(Reaper.java:322)
		at jenkins.util.Listeners.lambda$notify$0(Listeners.java:59)
		at jenkins.util.Listeners.notify(Listeners.java:67)
		at org.csanchez.jenkins.plugins.kubernetes.pod.retention.Reaper$CloudPodWatcher.eventReceived(Reaper.java:320)
		at org.csanchez.jenkins.plugins.kubernetes.pod.retention.Reaper$CloudPodWatcher.eventReceived(Reaper.java:280)
		at io.fabric8.kubernetes.client.utils.internal.WatcherToggle.eventReceived(WatcherToggle.java:49)
		at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.eventReceived(AbstractWatchManager.java:191)
		at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.onMessage(AbstractWatchManager.java:268)
		at io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener.onMessage(WatcherWebSocketListener.java:55)
		at io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl$1.onMessage(OkHttpWebSocketImpl.java:117)
		at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:333)
		at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:245)
		at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:106)
		at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
		at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
		at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
org.jenkinsci.plugins.workflow.support.steps.AgentOfflineException: Unable to create live FilePath for example-agent-n74z5; example-agent-n74z5 was marked offline: Pod failed (Reason: Evicted, Message: Pod ephemeral local storage usage exceeds the total limit of containers 4Gi. )
	at org.jenkinsci.plugins.workflow.support.steps.ExecutorStepDynamicContext$FilePathTranslator.get(ExecutorStepDynamicContext.java:182)
	at org.jenkinsci.plugins.workflow.support.steps.ExecutorStepDynamicContext$FilePathTranslator.get(ExecutorStepDynamicContext.java:154)
	at org.jenkinsci.plugins.workflow.support.steps.ExecutorStepDynamicContext$Translator.get(ExecutorStepDynamicContext.java:147)
	at org.jenkinsci.plugins.workflow.support.steps.ExecutorStepDynamicContext$FilePathTranslator.get(ExecutorStepDynamicContext.java:164)
	at org.jenkinsci.plugins.workflow.support.steps.ExecutorStepDynamicContext$FilePathTranslator.get(ExecutorStepDynamicContext.java:154)
</pre>
</details>

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by Angelin01** [comment]
I don't know if this PR is the appropriate one to add this to, but I've noticed that this plugin also doesn't handle unexpected connection drops well: the build **usually** hangs indefinitely. On our Jenkins this requires frequent script usage to kill stuck builds.

I looked at [how the code for the ec2-fleet-plugin handles this](https://github.com/jenkinsci/ec2-fleet-plugin/blob/master/src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetAutoResubmitComputerLauncher.java#L76-L118) I've tried to replicate it with a simple fix which half overlaps with this PR. I tried to sanitize it and include only the different code, however I feel like the `PodTerminatedCause` class is redundant.

```patch
From 68ffa1f4240c2b1bd0857a247f4a798a4ff11ba5 Mon Sep 17 00:00:00 2001
From: Angelo Ross <angelo.ross@objective.com.br>
Date: Thu, 20 Apr 2023 17:37:32 -0300
Subject: [PATCH] Handle still running jobs after pod disconnect

---
 .../kubernetes/KubernetesLauncher.java        | 31 +++++++++++++++++--
 .../kubernetes/PodTerminatedCause.java        | 17 ++++++++++
 2 files changed, 46 insertions(+), 2 deletions(-)
 create mode 100644 src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTerminatedCause.java

diff --git a/src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java b/src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
index d8e6b1e5..11568c78 100644
--- a/src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
+++ b/src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
@@ -27,6 +27,9 @@ package org.csanchez.jenkins.plugins.kubernetes;
 
 import edu.umd.cs.findbugs.annotations.CheckForNull;
 import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
+import hudson.model.Executor;
+import hudson.model.Queue;
+import hudson.model.Result;
 import hudson.model.TaskListener;
 import hudson.slaves.JNLPLauncher;
 import hudson.slaves.SlaveComputer;
@@ -177,7 +180,7 @@ public class KubernetesLauncher extends JNLPLauncher {
             // so wait for agent to be online
             int waitForSlaveToConnect = template.getSlaveConnectTimeout();
             int waitedForSlave;
-            
+
             SlaveComputer slaveComputer = null;
             String status = null;
             List<ContainerStatus> containerStatuses = null;
@@ -264,8 +267,32 @@ public class KubernetesLauncher extends JNLPLauncher {
         }
     }
 
+    @Override
+    public void afterDisconnect(SlaveComputer computer, TaskListener listener) {
+        if (computer == null) {
+            return;
+        }
+
+        final String podName = computer.getDisplayName();
+        LOGGER.info("Agent " + podName + " disconnected");
+
+        for (Executor executor : computer.getExecutors()) {
+            Queue.Executable executable = executor.getCurrentExecutable();
+            if (executable == null) {
+                continue;
+            }
+
+            executor.interrupt(Result.ABORTED, new PodTerminatedCause(podName));
+
+            final Queue.Task task = executable.getParent().getOwnerTask();
+            LOGGER.warning("Aborted " + task + "because its pod agent was terminated");
+        }
+
+        super.afterDisconnect(computer, listener);
+    }
+
     private void checkTerminatedContainers(List<ContainerStatus> terminatedContainers, String podId, String namespace,
-            KubernetesSlave slave, KubernetesClient client) {
+                                           KubernetesSlave slave, KubernetesClient client) {
         if (!terminatedContainers.isEmpty()) {
             Map<String, Integer> errors = terminatedContainers.stream().collect(Collectors
                     .toMap(ContainerStatus::getName, (info) -> info.getState().getTerminated().getExitCode()));
diff --git a/src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTerminatedCause.java b/src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTerminatedCause.java
new file mode 100644
index 00000000..a0f1cfe0
--- /dev/null
+++ b/src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTerminatedCause.java
@@ -0,0 +1,17 @@
+package org.csanchez.jenkins.plugins.kubernetes;
+
+import jenkins.model.CauseOfInterruption;
+
+public class PodTerminatedCause extends CauseOfInterruption {
+
+   final String podName;
+
+   public PodTerminatedCause(String podName) {
+       this.podName = podName;
+   }
+
+   @Override
+   public String getShortDescription() {
+       return "Pod " + podName + " was terminated";
+   }
+}
-- 
2.40.0
```

If this is relevant, @cronik feel free to add this code to your PR. If you prefer, I can open a PR against your own fork.

Otherwise, I can open a separate PR for this, although I might wait for this one to be merged first.

**Comment by cronik** [comment]
@Angelin01 Might be better to create a separate PR in case this one is not accepted and your change seems to stand on it's own.

What you could do is get the `computer.getOfflineCause()` and if not `null` append it to the `PodTerminationCause` description. If this PR is accepted is should get the reason from the Reaper otherwise it will probably be some generic message, but useful none the less.

```java
@Override
public void afterDisconnect(SlaveComputer computer, TaskListener listener) {
   // ...
   OfflineCause cause = computer.getOfflineCause();
   for (Executor executor : computer.getExecutors()) {
       // ...
      executor.interrupt(Result.ABORTED, new PodTerminatedCause(podName, cause));
   }
   // ...
}
```

**Comment by Angelin01** [comment]
@cronik Very well, I'll whip up a new PR. I'll try to write up a test if I figure out how Jenkins' testing works. Thanks for the original cause suggestion, hopefully this PR goes through as the information it provides would be great for me.

**Review by Vlatombe — APPROVED** [review]
LGTM. Sorry for the delay!

**Pull request merged**
