### PR TITLE
[JENKINS-64006] Documenting dynamicPVC for volumes

### PR DESCRIPTION
**Pull request by Dan-Heath**
This PR updates the Jenkins plugin documentation with the new `dynamicPVC` option that is being added for volumes through [JENKINS-64006](https://issues.jenkins.io/browse/JENKINS-64006).

- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [X] Link to relevant issues in GitHub or Jira
- [X] Link to relevant pull requests, esp. upstream and downstream changes
- [N/A] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by Vlatombe — CHANGES_REQUESTED** [review]
I think we should cover all current available implementations for volumes, since this was not listed before. Descriptions should be the same as what is under workspaceVolume.

https://github.com/jenkinsci/kubernetes-plugin/tree/8a57ef12bfc88877682f6fd9c3291833bfa61876/src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes

* `configMapVolume`
* `dynamicPVC`
* `emptyDirVolume`
* `hostPathVolume`
* `nfsVolume`
* `persistentVolumeClaim`
* `secretVolume`

**Comment by Dan-Heath** [comment]
> I think we should cover all current available implementations for volumes, since this was not listed before. Descriptions should be the same as what is under `workspaceVolume`.

Thanks @Vlatombe . I added the same implementations that exist under `workspaceVolume`, but I don't see descriptions for `configMapVolume` or `secretVolume`. Should we add something new for those 2?

**Comment by Vlatombe** [comment]
Yes possibly. `configMapVolume` mounts a readonly volume from a configmap, and `secretVolume ` the same but from a kubernetes secret.

**Comment by Dan-Heath** [comment]
> Yes possibly. `configMapVolume` mounts a readonly volume from a configmap, and `secretVolume ` the same but from a kubernetes secret.

Thanks @Vlatombe ! I added both values for `volume` and `workspaceVolume`.

**Comment by Vlatombe** [comment]
@Dan-Heath these options are not available for `workspaceVolume` as they are readonly.

**Comment by Dan-Heath** [comment]
> @Dan-Heath these options are not available for `workspaceVolume` as they are readonly.

Oops, that makes sense. I just got rid of those 2 options. Thank you @Vlatombe . I am not sure how this gets merged. Do you have rights?

**Review by Vlatombe — APPROVED** [review]

**Comment by fragolinux** [comment]
i can't get this to work for secrets or configmaps... i've this config in my helmrelease, and it works if i just leave the persistentVolumeClaim resource in there... once i add the configmap (which is just a test) or even 1 of the 2 secrets needed to access a nexus3 repo (and each of them exist in same jenkins namespace, cm and secrets), the resulting pod will include just the jnlp container and never the maven one...

```
        maven-0-7-0-nexus2: |
          - name: maven
            label: jenkins-maven-0-7-0-nexus2
            serviceAccount: jenkins
            containers:
              - name: maven
                image: ghcr.io/ecomind/jenkins-agent-maven:0.7.0
                command: "cat"
                ttyEnabled: true
                privileged: true
                resourceRequestCpu: "1"
                resourceRequestMemory: "2Gi"
                resourceLimitCpu: "2"
                resourceLimitMemory: "4Gi"
            volumes:
              - persistentVolumeClaim:
                  mountPath: /home/jenkins/.m2/repository
                  claimName: maven
                  readOnly: false
              - configMapVolume:
                  configMapName: cm-test
                  mountPath: /tmp/ui.properties
                  subPath: ui.properties
              - secretVolume:
                  mountPath: /home/jenkins/.m2
                  secretName: nexus-settings
              - secretVolume:
                  mountPath: /home/jenkins/.m2
                  secretName: nexus-settings-security
```

can't find an example of this, but what i did is coherent with official docs...

**Pull request merged**
