### PR TITLE
Allow reading logs and events with Computer.EXTENDED_READ instead of Jenkins.ADMINISTER

### PR DESCRIPTION
**Pull request by runzexia**
Signed-off-by: runzexia <runzexia@yunify.com>
@jglick @Vlatombe

### CODE REVIEW

**Comment by Vlatombe** [comment]
Could be a problem as container logs or structure could expose some secrets.

**Review by Vlatombe — APPROVED** [review]
lgtm

**Comment by jglick** [comment]
> Could be a problem as container logs or structure could expose some secrets.

Do you no longer believe this to be a risk?

**Comment by Vlatombe** [comment]
On the agent container it looks safe. For other containers, it could be debated to give access to logs.

**Pull request merged**
