### PR TITLE
Remove unused JENKINS_JNLP_URL env var

### PR DESCRIPTION
**Pull request by carlossg**

### CODE REVIEW

**Comment by marvinthepa** [comment]
What was this used for? When did this become obsolete? Just asking out of curiosity :-).

**Comment by Vlatombe** [comment]
It was used at one point in the slave image but got removed since (https://github.com/carlossg/jenkins-slave-docker/commit/4b0d0f7a8f36cc65acb47c31507fe52932f8577c).

**Comment by nehaljwani** [comment]
Just saw this today and upgrading plugin to v1.1 broke my builds. I have been using my own container to connect to the jenkins master and used the following command to do so:
```
${JAVA} ${JAVA_OPTS} -jar ${SLAVE_JAR} -jnlpUrl ${JENKINS_JNLP_URL} -secret ${JENKINS_SECRET} -noReconnect
```
Any chance that this could be brought back? What's the recommended way? Should I be generating this URL on my own now?

**Comment by Vlatombe** [comment]
Hi @nehaljwani 
you can use `${JENKINS_URL}/computer/${JENKINS_NAME}/slave-agent.jnlp` instead.

**Pull request merged**
