### PR TITLE
JENKINS-50429 combine env vars into a single set before writing once

### PR DESCRIPTION
**Pull request by mrjgreen**
* combine env vars before writing once into the container

### CODE REVIEW

**Comment by mrjgreen** [comment]
@carlossg - I tested this locally and it appears to have cut the time down to 1 second overhead instead of 3/4 seconds. As far as I can tell, the env vars are still being set... Does this look reasonable?

**Comment by carlossg** [comment]
makes sense. But I think I have tested something similar and didn't improve the speed, need to retest

**Comment by mrjgreen** [comment]
👍 

Is there anything we can do to address the root cause of the problem with the input.write() buffer? Would upgrading the JDK version in the jenkins containers be likely to help?

I'll look into this and see if the OutputStream know issue was ever resolved in any version.

**Comment by sylus** [comment]
Was wondering if there was any other progress against this?

**Comment by mrjgreen** [comment]
Our tests suggest that this does reduce the overhead of running sh commands - it reduced the overhead of a `date` sh command from 4 seconds to 2 seconds.

**Comment by carlossg** [comment]
Better than asking for progress it'd be good if you tried the pr and comment on whether it fixes the problem for you or not

**Comment by carlossg** [comment]
I have tested with this job and I'm still getting a big difference between shell execution inside a container.

|60 calls outside container | 60 calls in container | 1 call in container|
|---|---|---|
|19s | 53s | 1s|

```
def label = "exec-${UUID.randomUUID().toString()}"
podTemplate(label: label) {

    timestamps {
        node(label){
            stage('60 calls outside container'){
                for (i = 0; i <60; i++) {
                    sh "echo $i"
                }
            }
            stage('60 calls in container'){
                container("jnlp"){
                    for (i = 0; i <60; i++) {
                        sh "echo $i"
                    }
                }
            }
            stage('1 call in container'){
                container("jnlp"){
                    sh "for i in `seq 1 100`; do echo $i; done"
                }
            }
        }
    }
}
```

**Comment by carlossg** [comment]
Merging because it doesn't hurt

**Pull request merged**
