### PR TITLE
add ConfigMapKeyRefEnvVar and fieldRefEnvVar to set env from more sources

### PR DESCRIPTION
**Pull request by jenningsloy318**
and two sources to create ENV
1. ConfigMapKeyRefEnvVar to create env from configmap 
2. fieldRefEnvVar to create env from pod ObjectField(status.hostIP, status.podIP, ..etc)

Refer to https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#envvarsource-v1-core

### CODE REVIEW

**Comment by carlossg** [comment]
Thanks, although I'm trying to focus on #275 instead of adding fields for any possible value which will make the plugin too complex

**Comment by jenningsloy318** [comment]
Hi @carlossg:

Thanks for your info, I wonder when #275  is stable enough that we can use. I implemented this feature because current plugin missed some feature. 

I also need one feature that in the volume part, sometime to mount a volume, we still need to specify the subPath when multiple volumes are mounted under one mount point.

**Comment by carlossg** [comment]
#275 is done, please give it a try and see if this is still needed

**Comment by carlossg** [comment]
First, try without the `PersistentVolumeClaim`, the yaml should be only the pod definition, I don't even know if that would work
You have a missing space at `label'jnlp-slave'`
I think this is picking a different agent, do you have any other agents defined in jenkins config with label `jnlp-slave` ? try with a new label to see

**Comment by jenningsloy318** [comment]
@carlossg 

I just want to define only one agent, is it possible to use my image in `jnlp` instead of default one ?

**Comment by carlossg** [comment]
I meant you have more than one pod template defined in jenkins with the same label so when it runs it may be picking the other one instead of the one defined in your pipeline

**Pull request closed without merging**
