### PR TITLE
Instance cap is set to 0 when form field is empty

### PR DESCRIPTION
**Pull request by carlossg**
@reviewbybees

### CODE REVIEW

**Comment by KostyaSha** [comment]
And where is @reviewbybees ?

**Comment by ndeloof** [comment]
reviewbybees policy doesn't restrict plugin maintainer to accept a PR before it has been reviewed by cloudbees engineering.

**Comment by KostyaSha** [comment]
@ndeloof nice cheating, CB engineer sends PR as CB employee, then second says that he is maintainer and merges without review.

According to git log @ndeloof is not working at CloudBees at all
```
kubernetes-plugin$ git log | grep nicolas | grep -i gmail | wc -l
      26
kubernetes-plugin$ git log | grep nicolas | grep -i cloudbees | wc -l
       0
``` 
Ah, even funny, both not working at CloudBees:
```
integer$ git log | grep -i Carlos | uniq  -c
  74 Author: Carlos Sanchez <carlos@apache.org>
   1 Author: Carlos Sanchez <github@carlossanchez.eu>
```

**Comment by ndeloof** [comment]
I never said we don't work at CloudBees, just said as maintainer we are free to approve PR
also, we use our personal github account by convenience.

**Comment by KostyaSha** [comment]
@ndeloof right
The only effort from CB in this plugin i see from 
```
$ git log | grep -i cloudbees
Author: Jesse Glick <jglick@cloudbees.com>
```

**Comment by ndeloof** [comment]
company policy does not enforce we use cloudbees.com email to connect and contribute on github.
Please also find something useful to make your life happier and stop trolling everywhere around.

**Comment by carlossg** [comment]
@KostyaSha I am the original author of the plugin and I created the PR so there is some track of the features, but it was no necessary to go through CloudBees process, these are personal contributions

**Comment by KostyaSha** [comment]
@carlossg thanks for clarification.

**Pull request merged**
