### PR TITLE
Fix logic for waitUntilContainerIsReady

### PR DESCRIPTION
**Pull request by philk**
We were running into the issue the wait is meant to resolve so I tried it out. Looks like the logic got reversed somewhere along the way.

### CODE REVIEW

**Comment by volkangurel** [comment]
:+1:

**Comment by carlossg** [comment]
ping @iocanel

**Comment by iocanel** [comment]
@philk: Thanks for catching this. I tried that and it looks good!

@carlossg: +1

**Comment by JeanMertz** [comment]
@philk @iocanel @carlossg I'm not sure this is entirely fixed.

Before, I was also seeing the timeout issues as described in https://github.com/jenkinsci/kubernetes-plugin/pull/93#issuecomment-264127037.

Now, I've got a situation where I've got some `sh` logic wrapped in a `retry` block, and I'm seeing the timeout error happen the first time the retry block is executed, and then once the block is retried, the script moves forward as expected:

```
Still waiting to schedule task
kubernetes-cbc4406893db41a9aef2d9e5d526fca1-6e9ef3076ae06 is offline
Running on kubernetes-cbc4406893db41a9aef2d9e5d526fca1-6e9ef3076ae06 in /home/jenkins/workspace/blendle_core-api_jenkins-JAM5PI6ZOUNKGTGYGMINDN4KNK2PFRGQPKWNXCRMGAOHJME4OVZA
[Pipeline] {
[Pipeline] container
[Pipeline] {
[Pipeline] withEnv
[Pipeline] {
[Pipeline] retry
[Pipeline] {
[Pipeline] sleep
Sleeping for 1 sec
[Pipeline] sh
[blendle_core-api_jenkins-JAM5PI6ZOUNKGTGYGMINDN4KNK2PFRGQPKWNXCRMGAOHJME4OVZA] Running shell script
Waiting for container container [instance-1] of pod [kubernetes-cbc4406893db41a9aef2d9e5d526fca1-6e9ef3076ae06] to become ready.
[Pipeline] }
ERROR: Execution failed
java.io.IOException: Failed to execute shell script inside container [instance-1] of pod [kubernetes-cbc4406893db41a9aef2d9e5d526fca1-6e9ef3076ae06]. Timed out waiting for container to become ready!
	at org.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecDecorator$1.launch(ContainerExecDecorator.java:89)
	at hudson.Launcher$ProcStarter.start(Launcher.java:383)
	at org.jenkinsci.plugins.durabletask.BourneShellScript.launchWithCookie(BourneShellScript.java:147)
	at org.jenkinsci.plugins.durabletask.FileMonitoringTask.launch(FileMonitoringTask.java:61)
	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.start(DurableTaskStep.java:158)
Retrying
[Pipeline] {
[Pipeline] sleep
Sleeping for 1 sec
[Pipeline] sh

... from here on out the build continued as expected
```

* I can consistently reproduce this by rerunning the job.
* I can confirm that the containers _are_ actually ready rather quickly
* However, I can imagine the container not being ready _immediately_ when the first `sh` is triggered, so _some_ waiting is to be expected.

It's almost as if the watcher logic [here](https://github.com/philk/kubernetes-plugin/blob/adcdbed40d8f32c64f1aa7ce8ec3b301c072f5b7/src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java#L164-L181) never triggers the `MODIFIED` event, and thus it just waits for the timeout to finish.

The timeout does take quite a long time to happen (maybe 60 seconds?) before my retry logic kicks in.

**Comment by iocanel** [comment]
@JeanMertz: You are right! The watcher implementation does not check the pod reference by the event, but the pod in its previous state (before) the watch! That will never work! 

Let me fix that!

**Comment by iocanel** [comment]
@JeanMertz: It should look like this: https://github.com/jenkinsci/kubernetes-plugin/pull/97

Do you want to give it a spin?

**Comment by philk** [comment]
Nice catch, we had a `retry` in our Jenkinsfile from before (when there was a race for the pod to become ready) so we didn't notice this. Thanks for the fix!

**Pull request merged**
