### PR TITLE
Add copy constructor for ContainerTemplate

### PR DESCRIPTION
**Pull request by psiroky**
The copy constructor is very useful when creating a new template based
on an existing one. The new container usually needs some config changes
without affecting the original container.

### CODE REVIEW

**Comment by carlossg** [comment]
where would you use it ? 
I wouldn't like to add new apis that then people forget to update when adding new fields

**Comment by psiroky** [comment]
I am using this when creating new pod templates pragmatically. I have a blueprint pod template, with default list of containers which is being cloned/copied and adjusted accordingly (e.g. different image tag).

There are copy constructors in both `KubernetesCloud` and `PodTemplate`, so I figured this could be useful as well. I can of course workaround this by basically copy-pasting the same code into my sources.

**Comment by carlossg** [comment]
ok with me, but it needs a test that checks that `equals` and `toString` are the same

**Comment by carlossg** [comment]
thanks!

**Pull request merged**
