### PR TITLE
Fix/readme typo

### PR DESCRIPTION
**Pull request by Nodraak**
I fixed a typo in README.md and used the occasion to include the example in the `examples/` folder.

### CODE REVIEW

**Comment by carlossg** [comment]
thanks!, could you remove the renaming commit ? I'd rather keep `declarative.groovy`

**Comment by Nodraak** [comment]
I though the difference between both declarative examples would be more descriptive, but as you want, I'll rebase my branch.

Oh, and sorry for the initial message, I should have added: thank you for your work maintaining this jenkins plugin :)

**Comment by carlossg** [comment]
thanks

**Comment by Nodraak** [comment]
Hi!

It seems that the pipeline can't find the file `script.sh`, which has nothing to do with the provided example.

Are you using the [provided example](https://github.com/Nodraak/kubernetes-plugin/blob/3accbf10b152a2977ff7c7572f2f90820e418802/examples/declarative-multiple-containers.groovy) unmodified? If not, could you paste your Jenkinsfile?

Also, could you paste the Console Output of the pipeline? I just ran the above example (which works fine) and got this:
```
Started by user admin
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] podTemplate
[Pipeline] {
[Pipeline] node

Still waiting to schedule task
All nodes of label ‘mypod’ are offline

Agent mypod-2b6q1-z1qwf is provisioned from template Kubernetes Pod Template
Agent specification [Kubernetes Pod Template] (mypod): 

Running on mypod-2b6q1-z1qwf in /home/jenkins/workspace/test-pr-github
[Pipeline] {
[Pipeline] container
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Run maven)
[Pipeline] container

[Pipeline] {

[Pipeline] sh
[test-pr-github] Running shell script

+ mvn -version
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T19:49:05Z)
Maven home: /usr/share/maven
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8-openjdk/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.12-301.fc27.x86_64", arch: "amd64", family: "unix"
[Pipeline] }
[Pipeline] // container
[Pipeline] container
[Pipeline] {

[Pipeline] sh

[test-pr-github] Running shell script
+ /bin/busybox
BusyBox v1.28.3 (2018-04-03 20:29:50 UTC) multi-call binary.
BusyBox is copyrighted by many authors between 1998-2015.
Licensed under GPLv2. See source distribution for detailed
copyright notices.

Usage: busybox [function [arguments]...]
   or: busybox --list[-full]
   or: busybox --install [-s] [DIR]
   or: function [arguments]...

	BusyBox is a multi-call binary that combines many common Unix
	utilities into a single executable.  Most people will create a
	link to busybox for each function they wish to use and BusyBox
	will act like whatever it was invoked as.

Currently defined functions:
	[, [[, acpid, add-shell, addgroup, adduser, adjtimex, ar, arch, arp,
	arping, ash, awk, base64, basename, beep, blkdiscard, blkid, blockdev,
	bootchartd, brctl, bunzip2, bzcat, bzip2, cal, cat, chat, chattr,
	chgrp, chmod, chown, chpasswd, chpst, chroot, chrt, chvt, cksum, clear,
	cmp, comm, conspy, cp, cpio, crond, crontab, cryptpw, cttyhack, cut,
	date, dc, dd, deallocvt, delgroup, deluser, depmod, devmem, df,
	dhcprelay, diff, dirname, dmesg, dnsd, dnsdomainname, dos2unix, dpkg,
	dpkg-deb, du, dumpkmap, dumpleases, echo, ed, egrep, eject, env,
	envdir, envuidgid, ether-wake, expand, expr, factor, fakeidentd,
	fallocate, false, fatattr, fbset, fbsplash, fdflush, fdformat, fdisk,
	fgconsole, fgrep, find, findfs, flock, fold, free, freeramdisk, fsck,
	fsck.minix, fsfreeze, fstrim, fsync, ftpd, ftpget, ftpput, fuser,
	getopt, getty, grep, groups, gunzip, gzip, halt, hd, hdparm, head,
	hexdump, hexedit, hostid, hostname, httpd, hush, hwclock, i2cdetect,
	i2cdump, i2cget, i2cset, id, ifconfig, ifdown, ifenslave, ifplugd,
	ifup, inetd, init, insmod, install, ionice, iostat, ip, ipaddr, ipcalc,
	ipcrm, ipcs, iplink, ipneigh, iproute, iprule, iptunnel, kbd_mode,
	kill, killall, killall5, klogd, last, less, link, linux32, linux64,
	linuxrc, ln, loadfont, loadkmap, logger, login, logname, logread,
	losetup, lpd, lpq, lpr, ls, lsattr, lsmod, lsof, lspci, lsscsi, lsusb,
	lzcat, lzma, lzop, makedevs, makemime, man, md5sum, mdev, mesg,
	microcom, mkdir, mkdosfs, mke2fs, mkfifo, mkfs.ext2, mkfs.minix,
	mkfs.vfat, mknod, mkpasswd, mkswap, mktemp, modinfo, modprobe, more,
	mount, mountpoint, mpstat, mt, mv, nameif, nanddump, nandwrite,
	nbd-client, nc, netstat, nice, nl, nmeter, nohup, nproc, nsenter,
	nslookup, ntpd, nuke, od, openvt, partprobe, passwd, paste, patch,
	pgrep, pidof, ping, ping6, pipe_progress, pivot_root, pkill, pmap,
	popmaildir, poweroff, powertop, printenv, printf, ps, pscan, pstree,
	pwd, pwdx, raidautorun, rdate, rdev, readahead, readlink, readprofile,
	realpath, reboot, reformime, remove-shell, renice, reset, resize,
	resume, rev, rm, rmdir, rmmod, route, rpm, rpm2cpio, rtcwake, run-init,
	run-parts, runlevel, runsv, runsvdir, rx, script, scriptreplay, sed,
	sendmail, seq, setarch, setconsole, setfattr, setfont, setkeycodes,
	setlogcons, setpriv, setserial, setsid, setuidgid, sh, sha1sum,
	sha256sum, sha3sum, sha512sum, showkey, shred, shuf, slattach, sleep,
	smemcap, softlimit, sort, split, ssl_client, start-stop-daemon, stat,
	strings, stty, su, sulogin, sum, sv, svc, svlogd, swapoff, swapon,
	switch_root, sync, sysctl, syslogd, tac, tail, tar, taskset, tcpsvd,
	tee, telnet, telnetd, test, tftp, tftpd, time, timeout, top, touch, tr,
	traceroute, traceroute6, true, truncate, tty, ttysize, tunctl,
	ubiattach, ubidetach, ubimkvol, ubirename, ubirmvol, ubirsvol,
	ubiupdatevol, udhcpc, udhcpd, udpsvd, uevent, umount, uname, unexpand,
	uniq, unix2dos, unlink, unlzma, unshare, unxz, unzip, uptime, users,
	usleep, uudecode, uuencode, vconfig, vi, vlock, volname, w, wall,
	watch, watchdog, wc, wget, which, who, whoami, whois, xargs, xxd, xz,
	xzcat, yes, zcat, zcip
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate

[Pipeline] End of Pipeline
Finished: SUCCESS

Page generated: 04-May-2018 12:57:35 UTCREST APIJenkins ver. 2.107.2
```

**Comment by berni2288** [comment]
Hi,

I didn't modify the pipeline. I think the script.sh is automatically created by Jenkins to execute the code `sh '/bin/busybox'`. We are using Jenkins 2.116 and the latest updates of all plugins.
For some reason, the sh in the maven container works, but in the busybox cotainer it does not.

If you ask me, it's another glitch in kubernetes-plugin.

Output

```Started by user Kaszt Bernhard
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] podTemplate
[Pipeline] {
[Pipeline] node
Still waiting to schedule task
Jenkins doesn’t have label mypod
Agent mypod-gz9z7-vpf6h is provisioned from template Kubernetes Pod Template
Agent specification [Kubernetes Pod Template] (mypod): 

Running on mypod-gz9z7-vpf6h in /home/jenkins/workspace/test
[Pipeline] {
[Pipeline] container
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Run maven)
[Pipeline] container
[Pipeline] {
[Pipeline] sh
[test] Running shell script
+ mvn -version
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T19:49:05Z)
Maven home: /usr/share/maven
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8-openjdk/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.13.0-37-generic", arch: "amd64", family: "unix"
[Pipeline] }
[Pipeline] // container
[Pipeline] container
[Pipeline] {
[Pipeline] sh
[test] Running shell script
sh: /home/jenkins/workspace/test@tmp/durable-5f05961c/script.sh: not found
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline
ERROR: script returned exit code 127
Finished: FAILURE```

**Comment by carlossg** [comment]
check for existing conflicting pod templates in your configuration with the label `mypod`
You should be using unique labels, some examples in the README

**Comment by berni2288** [comment]
There are no conflicting pod templates. To be sure, I just deleted all templates in the system configuration and created a new pipeline job. Still the same error.

**Comment by carlossg** [comment]
I just tested it with 1.6.0 and works with the same output as @Nodraak pasted

**Comment by berni2288** [comment]
That's weird.

**Pull request merged**
