### PR TITLE
Update jackson2-api to 2.12.0

### PR DESCRIPTION
**Pull request by Vlatombe**
This brings support for octal numbers for fields specified through the `yaml` field.

### CODE REVIEW

**Comment by Vlatombe** [comment]
@schottsfired fyi

**Comment by schottsfired** [comment]
Nice 😄

**Review by schottsfired — APPROVED** [review]
Note https://github.com/jenkinsci/kubernetes-plugin/blob/e83e51f80a9f9b66655977af5711e1af09687aed/src/main/resources/org/csanchez/jenkins/plugins/kubernetes/volumes/SecretVolume/help-defaultMode.html#L1

**Comment by Vlatombe** [comment]
Still the case https://github.com/jenkinsci/kubernetes-plugin/blob/79336697f310a03bc2194d47ba99c9a024754d90/src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/SecretVolume.java#L62

**Pull request merged**
