### PR TITLE
Print a warning in build log for declarative deprecated options

### PR DESCRIPTION
**Pull request by Vlatombe**

### CODE REVIEW

**Comment by deiga** [comment]
@Vlatombe There are no docs about this deprecation and the warning message doesn't really elaborate on how to replace the `label`. `inheritFrom` seems the wrong choice for us, as we use `label` to differentiate workers, but `name` does not exist for agent of type kubernetes.

Could you add some docs describing the options here?

**Comment by sodul** [comment]
@Vlatombe We are quite confused ourselves.

If we have a pipeline declared as such:
```
pipeline {
    agent {
        kubernetes {
            label "${env.JOB_BASE_NAME}"
            defaultContainer 'jnlp'
            yaml """\
apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: ${env.JOB_BASE_NAME}
spec:
  imagePullSecrets:
    - name: regsecret
"""
         }
     }
    stages {
        stage('Dep') {
            steps {
                sh "echo chuck"
            }
        }
    }
    post { always { chuckNorris()}}
}
```
What do we do instead?

**Comment by Moskovych** [comment]
@Vlatombe , +1 for previous comment.
If a `label` isn't specified, our pods have auto-generated names.
Are there any documentation of replacement and how to force keep custom name of pods?

**Comment by deiga** [comment]
@Vlatombe @jglick Could anyone please respond to this question?

**Comment by jglick** [comment]
Normally you should just delete `label`. It is no longer necessary. If you _must_ have some custom format for pod names for some reason, then you can continue to use it (or Scripted syntax).

**Comment by deiga** [comment]
@jglick As far as I understand re-using pods is based on the label of the pod. If all pods have custom names, then each job needs to always spin up a new pod, right? We have multiple pod types based on what job it needs to run and allowance of ~15min after each job run so that that pod could be re-used and avoid spin-up time

**Comment by jglick** [comment]
> each job needs to always spin up a new pod, right?

That is the intent of this plugin, yes. There is no tested facility (AFAIK) for reusing pods across builds and I would strongly discourage attempts to do so. (To save, what, a few seconds?) If you want to try “pushing the envelope” like this, it is best to use Scripted syntax with `podTemplate` to define exactly what you want to happen.

**Comment by deiga** [comment]
> > each job needs to always spin up a new pod, right?
> 
> That is the intent of this plugin, yes. There is no tested facility (AFAIK) for reusing pods across builds and I would strongly discourage attempts to do so. (To save, what, a few seconds?) If you want to try “pushing the envelope” like this, it is best to use Scripted syntax with `podTemplate` to define exactly what you want to happen.

Thank you very much for the clarification! Have a nice day 😄

**Comment by bb-benjaminl** [comment]
Is there a timeline for removal of these deprecated features?  We have been using the `label` and need to understand how critical it is that we migrate to `inheritFrom` - we have a few hundred developers maintaining their own pipelines that use `label` so it's not a small effort to communicate and get the work scheduled.

**Comment by Vlatombe** [comment]
@bb-benjaminl I don't have a timeline to remove it at the moment.

**Comment by dariodsa** [comment]
Has anything changed regarded a timeline?

**Pull request merged**
