### PR TITLE
[JENKINS-64322] client key algo should be configurable

### PR DESCRIPTION
**Pull request by olamy**
Signed-off-by: Olivier Lamy <olamy@apache.org>

### CODE REVIEW

**Comment by Vlatombe** [comment]
I think https://github.com/fabric8io/kubernetes-client/issues/3535 is better than asking users to provide a magic string.

**Comment by olamy** [comment]
> I think [fabric8io/kubernetes-client#3535](https://github.com/fabric8io/kubernetes-client/issues/3535) is better than asking users to provide a magic string.


maybe but the fix in the `kubernetes-client` code looks to be available when using `loadFromKubeconfig`.
Does the fix work when the cloud you configured is the different one than the one configured in `$HOME/.kube/config`?
In my use case, I configure 2 kube cloud: one has the default configuration on master node in `$HOME/.kube/config` but the second one not.

**Comment by olamy** [comment]
> I think [fabric8io/kubernetes-client#3535](https://github.com/fabric8io/kubernetes-client/issues/3535) is better than asking users to provide a magic string.

nice finding!
I did some testing and definitely confirm this work with `kubernetes-client-api-5.11-SNAPSHOT-SNAPSHOT.hpi` (I like the naming :) )

**Comment by Vlatombe** [comment]
Should be fixed through https://github.com/jenkinsci/kubernetes-plugin/pull/1101

**Pull request closed without merging**
