### PR TITLE
Avoid streaming to 2 similar OutputStreams

### PR DESCRIPTION
**Pull request by yahavi**
I have an issue when running launcher.launch().stdout(listener) from a different plugin. 

**Background**: 
ContainerExecDecorator decorates the launcher. 

**The issue:**
ContainerExecDecorator's `doLaunch()` gets an OutputStream and splits the output to both the outputForCaller and launcher's logger. In my case, outputForCaller and launcher's logger are the same.

**Expected:** 
All lines printed properly in job's log

**Actual:** 
Lines are printed twice in job's log

**Reconstruction:**
Run [this line](https://github.com/jfrog/project-examples/blob/master/jenkins-examples/pipeline-examples/scripted-examples/maven-example/Jenkinsfile#L18) inside a pod:
```
container('maven') {
    rtMaven.run pom: 'maven-example/pom.xml', goals: 'clean install', buildInfo: buildInfo
}
```

This issue is resolved in 2018 by https://github.com/jenkinsci/kubernetes-plugin/pull/356 and probably reintroduced by https://github.com/jenkinsci/kubernetes-plugin/commit/59a32abad3f5587b8574cb5f28a4139077140ef6.
For more information see: https://github.com/jfrog/project-examples/issues/249

### CODE REVIEW

**Comment by Vlatombe** [comment]
This needs a unit test to avoid future regressions.

**Comment by yahavi** [comment]
@Vlatombe 
Can you guide me on how to write unit tests that check the log output of this command?
Thanks!

**Comment by Vlatombe** [comment]
Look at https://github.com/jenkinsci/kubernetes-plugin/blob/c5d7cfc307f6579cb982992c4fd2f5b03caad637/src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorTest.java#L254-L261. If I understand the use case properly, you will need to pass a listener to `DummyLauncher` and also to `starter.stdout(listener)`, then check the output stream for duplicates.

**Comment by yahavi** [comment]
@Vlatombe I added a unit test. 
Please review.

**Review by Vlatombe — APPROVED** [review]
lgtm

**Pull request merged**
