### PR TITLE
PodTemplate: Memoize label set

### PR DESCRIPTION
**Pull request by amorken**
As the label set on every PodTemplate is accessed and matched rather frequently while the hudson.model.Queue lock is held, parsing the labels for every pod template can be rather costly for larger Jenkins hosts that manage O(1000) pod templates, and this cost is easily avoided with non-invasive memoization.

This issue has been observed in the wild by inspecting thread stacks of an underperforming Jenkins master. Many threads were found to be blocked waiting for the main Queue lock, and the single thread holding the Queue lock was frequently found to be busy parsing PodTemplate labels. A more invasive but probably even more effective mitigation would involve maintaining a map of labels by name for each pod template or perhaps even a multimap of pod templates by label name for each KubernetesCloud instance, but as such a change would be more invasive we've opted to try this first.

### CODE REVIEW

**Comment by AnEmortalKid** [comment]
We've also seen this issue, the threaddump looks something like this:
```
"Computer.threadPoolForRemoting [#40534]" - Thread t@660879
   java.lang.Thread.State: RUNNABLE
        at hudson.util.QuotedStringTokenizer.<init>(QuotedStringTokenizer.java:128)
        at hudson.model.Label.parse(Label.java:613)
        at org.csanchez.jenkins.plugins.kubernetes.PodTemplate.getLabelSet(PodTemplate.java:419)
        at org.csanchez.jenkins.plugins.kubernetes.PodTemplateUtils.getTemplateByLabel(PodTemplateUtils.java:496)
        at org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud.getTemplate(KubernetesCloud.java:649)
        at org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud.canProvision(KubernetesCloud.java:640)
        at hudson.model.Label.getClouds(Label.java:256)
        at hudson.model.Label.isEmpty(Label.java:459)
        at jenkins.model.Jenkins.trimLabels(Jenkins.java:2204)
        at jenkins.model.Nodes$6.run(Nodes.java:272)
        at hudson.model.Queue._withLock(Queue.java:1398)
        at hudson.model.Queue.withLock(Queue.java:1275)
        at jenkins.model.Nodes.removeNode(Nodes.java:262)
        at jenkins.model.Jenkins.removeNode(Jenkins.java:2165)
        at hudson.slaves.AbstractCloudSlave.terminate(AbstractCloudSlave.java:93)
        at org.jenkinsci.plugins.durabletask.executors.OnceRetentionStrategy$1$1.run(OnceRetentionStrategy.java:128)
        at hudson.model.Queue._withLock(Queue.java:1398)
        at hudson.model.Queue.withLock(Queue.java:1275)
        at org.jenkinsci.plugins.durabletask.executors.OnceRetentionStrategy$1.run(OnceRetentionStrategy.java:123)
        at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
        at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - locked <21116b20> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)

        - locked <22fe29d4> (a java.util.concurrent.ThreadPoolExecutor$Worker)

And Many Instances of (about 58 in our sample stack trace)

"Executor #0 for anotherPodWaitingToLaunch" - Thread t@660951
   java.lang.Thread.State: WAITING
        at sun.misc.Unsafe.park(Native Method)
        - waiting to lock <21116b20> (a java.util.concurrent.locks.ReentrantLock$NonfairSync) owned by "Computer.threadPoolForRemoting [#40534]" t@660879
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
        at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
        at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
        at hudson.model.Queue._withLock(Queue.java:1455)
        at hudson.model.Queue.withLock(Queue.java:1318)
        at hudson.model.Executor.run(Executor.java:346)

   Locked ownable synchronizers:
        - None

"Executor #0 for someJob1" - Thread t@660870
   java.lang.Thread.State: WAITING
        at sun.misc.Unsafe.park(Native Method)
        - waiting to lock <21116b20> (a java.util.concurrent.locks.ReentrantLock$NonfairSync) owned by "Computer.threadPoolForRemoting [#40534]" t@660879
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
        at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
        at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
        at hudson.model.Queue._withLock(Queue.java:1455)
        at hudson.model.Queue.withLock(Queue.java:1318)
        at hudson.model.Executor.run(Executor.java:346)

   Locked ownable synchronizers:
        - None
```

**Comment by Vlatombe** [comment]
@amorken Looks good to me. Could you fix the conflicts and mark the PR as ready for review?

**Comment by Vlatombe** [comment]
Is it still necessary now that #880 has been addressed?

**Comment by Vlatombe** [comment]
Closing as stale.

**Pull request closed without merging**
