### PR TITLE
The workspace volume is now configurable.

### PR DESCRIPTION
**Pull request by iocanel**
Currently containers share workspace by accessing an empty dir volume inside the pod.

We should also allow the use of other means, like pvc, nfs and hostpath volumes.

This pull request adds an option that alllows the user to choose and configure one of the above.

This is still work in progress (still need to do some more testing), but I am creating the PR for feedback etc.

### CODE REVIEW

**Comment by iocanel** [comment]
@carlossg: any comments?

**Comment by iocanel** [comment]
One of the issues, I have with this pull request is that I can't get the optional block to work correctly (the checkbox  that shows the block that lets you define a  work space volume).

I am using an optionalBlock and the issue I have is that the configuration is not persisted. 

@carlossg: could you help me a bit with that.

I also have the exact same issue with #117

**Comment by carlossg** [comment]
No idea, would need to check it this weekend. 

I'd check with the browser dev tools what form data is sent from the browser to the backend, that could give you a hint

**Comment by iocanel** [comment]
ahhhh great idea!

**Comment by iocanel** [comment]
@carlossg: I think its ready for review now.

**Comment by carlossg** [comment]
LGTM, I would love to have some examples in the README and some testing with minikube in KubernetesPipelineTest otherwise this is going to be a nightmare to maintain and avoid regressions

**Pull request merged**
