### PR TITLE
check for null prior to ranging over template.getEnvVars()

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@carlossg since it's not clear that https://github.com/jenkinsci/kubernetes-plugin/pull/59 will be necessary, i've split out the null pointer fix to this PR.

**Comment by carlossg** [comment]
Thanks. The formatting is bad again, different than the reset of the class in indentation, spaces,...

**Comment by bparees** [comment]
@carlossg converted to spaces

**Comment by bparees** [comment]
@carlossg bump

**Comment by bparees** [comment]
on further investigation it appears the NPE issue arises when there is no \<envVar\> section defined at all in the pod template.  as long as you have \<envVar\\\> things are ok, but this still seems like a useful fix.

**Comment by carlossg** [comment]
Thanks

**Pull request merged**
