### PR TITLE
[JENKINS-50392] Get the exit code the correct way

### PR DESCRIPTION
**Pull request by carlossg**
Use the error websocket stream to get the info

Depends on https://github.com/fabric8io/kubernetes-client/pull/1045

### CODE REVIEW

**Comment by giannello** [comment]
@carlossg would you mind letting me know when this is ready to be tested?

**Comment by carlossg** [comment]
All tests passing, it's ready with the fabric8 PR

**Comment by giannello** [comment]
Awesome, will give it a spin. Thanks!

**Comment by giannello** [comment]
@carlossg confirmed working!
```
11:39:35 Executing shell script inside container [maven] of pod [maven-docker-jdbt4-j7rdt]
11:39:36 Executing command: "printenv" "MAVEN_HOME" 
11:39:36 exit
11:39:36 /usr/share/maven
11:39:36 [withMaven] using Maven installation provided by the build agent with the environment variable MAVEN_HOME=/usr/share/maven
```

No more stray `EXITCODE`, thanks for the amazingly quick fix!

**Comment by balihb** [comment]
anything I can help with this?

**Comment by carlossg** [comment]
something you can help with is test and +1 at  fabric8io/kubernetes-client#1045

**Comment by carlossg** [comment]
You can get the latest plugin `hpi` from https://jenkins.gke.csanchez.org/job/jenkinsci/job/kubernetes-plugin/job/JENKINS-50392-exit-code/lastSuccessfulBuild/artifact/target/

**Comment by balihb** [comment]
works great!!!

my test cases:
```groovy
    cxnBuildStage ('env chk') {
      withEnv(['VARTOPRINT=vartoprint']) {
        if(sh(script: "echo \$VARTOPRINT", returnStdout: true).trim() != 'vartoprint') {
          error('env var not propagated to shell')
        }
      }
    }

    cxnBuildStage ('sshagent chk') {
      sshagent(['ssh-user']) {
        if(sh(script: "ssh -o StrictHostKeyChecking=no ssh-user@sshserver 'echo something'", returnStdout: true).trim() != 'something') {
          error('nothing printed via ssh')
        }
      }
    }

    cxnBuildStage ('withRun') {
      docker.image('mysql:5').withRun('-e "MYSQL_ROOT_PASSWORD=my-secret-pw"') { c ->
        def mysqlIp = sh(script: "docker inspect -f {{.NetworkSettings.IPAddress}} ${c.id}", returnStdout: true).trim()
        timeout(60) {
          sh "while ! mysqladmin ping -h${mysqlIp} --silent; do sleep 1; done"
        }
      }
    }

    cxnBuildStage ('build') {
      sh './gradlew build'
    }
```

**Comment by balihb** [comment]
I've found a relatively serious problem. If I say this in the code:
```groovy
docker.withRegistry("https://${env.MY_DOCKER_HUB}", 'my-docker-hub-user-cred-id') {
```
the build console output writes out:
```
Executing command: "docker" "login" "-u" "THE_ACTUAL_USERNAME" "-p" "THE_ACTUAL_PASSWORD" "THE_ACTUAL_DOCKER_REGISTRY_URL"
```
which shouldn't be printed at all and this is a serious security risk.

**Comment by carlossg** [comment]
To @balihb and others that received his comment, please do not disclose security issues publicly, use https://issues.jenkins-ci.org/browse/SECURITY
That said, there is already one filed.

**Comment by balihb** [comment]
this is a security issue with this PR.

**Comment by carlossg** [comment]
The security issue is now public and fixed in 1.7.1, it was not just with this PR 
https://github.com/jenkinsci/kubernetes-plugin/blob/master/CHANGELOG.md#171

**Pull request merged**
