### PR TITLE
[JENKINS-50429] Use a bigger buffer for stdin on kubernetes exec

### PR DESCRIPTION
**Pull request by carlossg**
Fixes #425
Works around https://github.com/fabric8io/kubernetes-client/issues/1008

### CODE REVIEW

**Comment by carlossg** [comment]
Please comment here what buffer size you need for your pipelines to work so we set a good default.
Try it setting a system property with the size

```
-Dorg.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecDecorator.stdinBufferSize=2048
```

**Comment by fabricepipart1a** [comment]
Sounds nice! Did it solve the performance issues mentioned?

**Comment by mrjgreen** [comment]
This is great news!

An typical command we run might be a ~100 bytes in length. Combining this with the set of env variables typically sent along with the command on exec looks to be around 4000 bytes.

I'm not sure if there is any other data sent along with the command (global variables etc?). I suspect 8192 bytes would suffice in most cases - though this isn't very scientific...

**Comment by carlossg** [comment]
yes, this solves the performance and the test pass

**Pull request merged**
