### PR TITLE
added Always imagePullPolicy to always pull latest image

### PR DESCRIPTION
**Pull request by azweb76**
If we need to update one of the slave images, we push a change to a slave repo which Jenkins will build and publish to our private registry. This will enable the Kubernetes Plugin to auto pull the latest on all Kubernetes nodes after an updated slave image becomes available.

### CODE REVIEW

**Comment by carlossg** [comment]
IMO this should be a config option in the template definition instead of forcing the pull always

**Comment by ndeloof** [comment]
Agree, could be a template configuration option but not default behaviour nor hidden one

**Comment by azweb76** [comment]
The behavior is already to pull the latest image, just not when it gets updated. I would assume that it would be a pain to spin through 100 nodes in a cluster and manually pull the latest image. Part of the CI/CD process would be to deploy the latest when it gets pushed to the registry. In this case, deploy it to the k8s nodes when the image is promoted to the latest/production tag in a docker registry.

**Comment by ndeloof** [comment]
I understand well your use case, but other docker-related plugins do offer such a "forcePull" advanced option, so to make the UX homogeneous I'd prefer to follow this approach. Please also note the default docker behavior is the same : even pulling does only imply some last modified check, it only occurs when user do explicitly ask for it.

**Comment by carlossg** [comment]
this is handled in #56

**Pull request closed without merging**
