### PR TITLE
Split credentials classes into new plugin kubernetes-credentials

### PR DESCRIPTION
**Pull request by maxlaverse**
Hi,
This remove the two OpenShift credentials implementation and the TokenProducer interface in favor of the `kubernetes-credentials` plugin, as discussed in https://github.com/jenkinsci/kubernetes-plugin/pull/223.

Do you want push rights on `kubernetes-credentials` @carlossg ?
Do you want to keep the OpenShift implementations here ?

Regards

### CODE REVIEW

**Comment by carlossg** [comment]
Push rights would be nice, thanks.
I'm concerned that with the package name change there will be issues upgrading, need to check

**Comment by maxlaverse** [comment]
I asked the jenkins-infra team to give you permissions on GitHub and Artifactory.
I aleady manually added you as collaborator on the repo.

I'm pretty sure the change of package for the implementations will require people to update their credentials if they have some. The move of the TokenProducer interface should be fine as it's only referenced in the code, not in the configuration.

I see multiple solutions:
* keep the two OpenShift implementations here, remove them from kubernetes-credentials
* keep the OS implementations here but add a "deprecated" mention in their names as displayed in the UI
* remove the OpenShift implementation from here and add a breaking change note in the changelog (might be alright if only a few people are using the implementation)

**Comment by carlossg** [comment]
I have kept the implementations here extending the kubernetes-credentials ones, set as deprecated. Upgrades should automatically handle the class renaming

**Comment by maxlaverse** [comment]
Ok great !
I'll update to remove the `KubectlWrapper` soon

**Pull request merged**
