### PR TITLE
Rename JENKINS_NAME to JENKINS_AGENT_NAME

### PR DESCRIPTION
**Pull request by ctavan**
This was changed in
https://github.com/jenkinsci/docker-jnlp-slave/commit/96c1c94

### CODE REVIEW

**Comment by jredl-va** [comment]
I don't think this is a safe change. I worked around this myself by customizing jnlp-slave however, the bash script in the repo you mentioned probably should be modified to set this value so it also works for backwards compatability.

**Comment by jredl-va** [comment]
Note, I have opened a PR here for the JNLP slave: https://github.com/jenkinsci/docker-jnlp-slave/pull/28

**Comment by ctavan** [comment]
@jredl-va I agree that it is probably safer to fix the docker image, thanks for the fix.

I'll leave it up to the maintainers of the kubernetes-plugin to decide how to deal with this proposal. Until then I will most likely also use the updated `docker-jnlp-slave` since jenkinsci/docker-jnlp-slave#28 has just been merged.

**Comment by er1c** [comment]
The change seems to have been merged in the https://github.com/jenkinsci/docker-jnlp-slave/pull/28, this PR can probably be closed

**Pull request closed without merging**
