### PR TITLE
[JENKINS-29213] configure k8s server certificate

### PR DESCRIPTION
**Pull request by ndeloof**

### CODE REVIEW

**Comment by ndeloof** [comment]
@reviewbybees

**Comment by stephenc** [comment]
:bee: (it would be better if the server cert was held by the credentials plugin, but that is more a desired end game and not a blocker on this change)

**Comment by carlossg** [comment]
@ndeloof can the section about server certificate in https://github.com/jenkinsci/kubernetes-plugin/blob/master/README.md#configuration-on-google-container-engine be removed now?

**Comment by ndeloof** [comment]
yes indeed, I'll update it

**Pull request merged**
