### PR TITLE
[JENKINS-44337] Add support for imagePullSecrets in pipeline

### PR DESCRIPTION
**Pull request by carlossg**
Can be added as

    podTemplate(imagePullSecrets: [ 'pull-secret' ])

### CODE REVIEW

**Comment by iocanel** [comment]
Tried to resolve conflict via github gui, but didn't seem to work. Can you please resolve the conflict?

**Comment by carlossg** [comment]
it looks like it was merged ok
what's the missing nested/inheritance? it was already in PodTemplate, just not in the Step

**Comment by zdraganov** [comment]
+1

**Comment by carlossg** [comment]
ping @iocanel

**Comment by iocanel** [comment]
@carlossg: Shouldn't we also add it here: https://github.com/jenkinsci/kubernetes-plugin/blob/master/src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java  as part of the combine method?

**Comment by carlossg** [comment]
it was already there https://github.com/jenkinsci/kubernetes-plugin/blob/master/src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java#L97

**Comment by iocanel** [comment]
@carlossg: doh! Sorry for that I didn't realize that.

**Comment by redr0bin** [comment]
When is the plugin version with this fix planned to be released ?

**Comment by haimari** [comment]
Is it possible to use imagePullSecrets at the global pod template level ?
Could not find documentation about how to pull from private repository when using kubernetes plugin with jenkins

**Comment by Hokwang** [comment]
This needs to add in declarative pipeline.

**Comment by darvein** [comment]
imagePullSecrets doesn't work on Declarative pipeline.

**Pull request merged**
