### PR TITLE
JENKINS-67100 - Ensure KubernetesProvisioningLimits is initialized before registering agents

### PR DESCRIPTION
**Pull request by mbarbero**
Fix for https://issues.jenkins.io/browse/JENKINS-67100.

AFAICT, `KubernetesProvisioningLimits#init` can be triggered after some calls to `KubernetesProvisioningLimits#register` have been made, creating "impossible" limits numbers (e.g. 32/4)

I identified that those registrations are done when some agents were running before Jenkins has been terminated. In this case, `NodeProvisionerInvoker` is invoked during Jenkins startup before the call of the `KubernetesProvisioningLimits#init` method.

This patch introduces a `CountDownLatch` that signals when `#init` has been called once it has counted down to zero. `#register()` and `#unregister()` await this signal before proceeding. 

Synchronization in the `#init` method is not needed anymore as we now have the latch.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by Vlatombe** [comment]
So what you mean here is that cloud provisioning is starting before limits are initialized.

Given
https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/PeriodicWork.java#L104-L105,

I think something like

```
    @Initializer(after = InitMilestone.SYSTEM_CONFIG_LOADED, before = InitMilestone.JOB_CONFIG_ADAPTED))
    public static void init() {
```

would achieve the same result.

**Comment by mbarbero** [comment]
Thanks for the feedbacks. I did not know we can specify both before and after :) I'll give it a try shortly and report back.

**Comment by mbarbero** [comment]
Your proposal works. It prevents `NodeProvisionerInvoker` from being called before the execution of `KubernetesProvisioningLimits#init` completed.

However, it does not fix the issue for the class `KubernetesProvisioningLimits$NodeListenerImpl`. It is still called at startup before `KubernetesProvisioningLimits#init` completed (see the stack trace below).

I've tried adding a static method with annotation `@Initializer(after = InitMilestone.JOB_CONFIG_ADAPTED)`, but it does not prevent the `#onDeleted` method from being invoked before the end of the execution of `KubernetesProvisioningLimits#init`.

It's not a breaking behavior, but it leads to logs `Global count for kubernetes went below zero. There is likely a bug in kubernetes-plugin` and `Pod template count for basictemplate went below zero. There is likely a bug in kubernetes-plugin`. It should be prevented IMO.

Any idea how to do that? 

```
org.csanchez.jenkins.plugins.kubernetes.KubernetesProvisioningLimits$NodeListenerImpl.onDeleted(KubernetesProvisioningLimits.java:151)
	jenkins.model.NodeListener.fireOnDeleted(NodeListener.java:98)
	jenkins.model.Nodes.removeNode(Nodes.java:287)
	jenkins.model.Jenkins.removeNode(Jenkins.java:2205)
	hudson.slaves.AbstractCloudSlave.terminate(AbstractCloudSlave.java:92)
	org.jenkinsci.plugins.durabletask.executors.OnceRetentionStrategy$1$1.run(OnceRetentionStrategy.java:128)
	hudson.model.Queue._withLock(Queue.java:1390)
	hudson.model.Queue.withLock(Queue.java:1266)
	org.jenkinsci.plugins.durabletask.executors.OnceRetentionStrategy$1.run(OnceRetentionStrategy.java:123)
	jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
```

**Comment by Vlatombe** [comment]
Right. It's a corner case on Jenkins startup, I think it should just do nothing until the limit counters are initialized. Since the initialization goes through every node, we know counters will be correct once it has run.

Something like
```
Jenkins j = Jenkins.getInstanceOrNull();
if (j == null || j.getInitLevel().compareTo(InitMilestone.JOB_CONFIG_ADAPTED) < 0) {
    // Counters haven't been initialized yet, so we can't do anything
    return;
}
```
in NodeListenerImpl#onDeleted

**Comment by mbarbero** [comment]
```java
Jenkins j = Jenkins.getInstanceOrNull();
if (j == null || j.getInitLevel().compareTo(InitMilestone.JOB_CONFIG_ADAPTED) < 0) {
    // Counters haven't been initialized yet, so we can't do anything
    return;
}
```

The code sample above, while probably working in most cases, is not safe as the comparison to the current Jenkins' `initLevel` and the action is not done atomically. Counters could be initialized between the test and the `return`. 

WDYT?

**Comment by Vlatombe** [comment]
Should be ensured since init block and register/unregister are `synchronized`

**Comment by mbarbero** [comment]
What I meant is that `NodeListenerImpl#onDeleted` could `return` without unregistering the node while the counters have been properly initialized when done. This can happen with aboce code when counters init happen between the `if` condition and the actual `return`. I don't see how it relates to `synchronized` blocks.

**Comment by mbarbero** [comment]
> What I meant is that `NodeListenerImpl#onDeleted` could `return` without unregistering the node while the counters have been properly initialized. This can happen with above code when counters init happens between the `if` condition and the actual `return`. I don't see how it relates to `synchronized` blocks.

WDYT?

**Comment by Vlatombe** [comment]
Sorry for the response time, I got busy with other tasks.

I've been running this in my head and considering

* Counter initialization locks queue
* Node deletion locks queue
* Node listener `#onDeleted` is called after releasing the queue lock

I don't think it would really miss events : the scenario you describe doesn't seem to be a problem so me, because by the time `#onDeleted` is called, the node has already been removed from the nodes registry, so if the counter init runs between `if` and `return` the node would be already gone and it wouldn't need to be unregistered.

However there is still a window for a race condition on initialization. If we have an event sequence as follow:

* Init milestone between `SYSTEM_CONFIG_LOADED` and `JOB_CONFIG_ADAPTED`
* [Node deletion](https://github.com/jenkinsci/jenkins/blob/e27b310065b3c036b5fc9d123f1d1d99d3058c00/core/src/main/java/jenkins/model/Nodes.java#L270-L283)
* Counter initialization
* Init milestone reaches `JOB_CONFIG_ADAPTED`
* `NodeListenerImpl#onDeleted` would unregister the node even though it wasn't taken into account in the counter initialization.

Since no synchronization is involved when calling the listener, I think we can't guarantee absence of drift, unless we perform a full counter resync.

**Comment by mbarbero** [comment]
closing in favor of #1144

**Pull request closed without merging**
