### PR TITLE
Don't provision when Jenkins is quieting down

### PR DESCRIPTION
**Pull request by schottsfired**
Fixes an issue where the K8s Plugin provisions agents while Jenkins is quieting down.

### CODE REVIEW

**Review by jglick — CHANGES_REQUESTED** [review]
This should happen in Jenkins core, not every plugin defining a `Cloud`.

**Review by Vlatombe — CHANGES_REQUESTED** [review]
Yes this should be a fix in core.

**Comment by schottsfired** [comment]
SGTM @jglick & @Vlatombe 

https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/slaves/Cloud.java#L173-L202 looks like a better place for the check.

**Comment by jglick** [comment]
That is the interface method. The check should be done in whatever code _calls_ that method.

**Comment by schottsfired** [comment]
Hmm, there is only one usage here in the default node provisioner strategy:
https://github.com/jenkinsci/jenkins/blob/b7020adab9e76643e345601392a8a3b97d6458d0/core/src/main/java/hudson/slaves/NodeProvisioner.java#L729

So I guess somewhere near this other check would work:
https://github.com/jenkinsci/jenkins/blob/b7020adab9e76643e345601392a8a3b97d6458d0/core/src/main/java/hudson/slaves/NodeProvisioner.java#L705-L707

**Comment by jglick** [comment]
Or probably at a higher level: https://github.com/jenkinsci/jenkins/blob/b7020adab9e76643e345601392a8a3b97d6458d0/core/src/main/java/hudson/slaves/NodeProvisioner.java#L820-L823

**Comment by schottsfired** [comment]
Ah, right! I was wondering about that, since there can be more than one node provisioning implementation. That location should catch them all.

**Comment by jglick** [comment]
Yes, or in `update` if we wanted to also ignore explicit calls to `suggestReviewNow()` (no strong opinion).

**Pull request closed without merging**
