### PR TITLE
[WIP] Add convenience variable "current_pod_label" in the body of podTemplate

### PR DESCRIPTION
**Pull request by marvinthepa**
So you can't use the wrong label when requesting a node inside.
Also makes 'label' optional, see example.

@carlossg @iocanel:
This is not ready for merging yet, just wanted to get feedback if you like the approach.

Will add tests/docs if I get the okay to continue.

I am not sure about the name of the "environment" variable - should it be different/camelCased? I actually just wanted an ordinary "groovy" variable for this, but only found the hack to add it to the environment, hence being also directly available as `current_pod_label`.

If you like the approach, I maybe could also add a step like

```
podTemplate(
        containers: [
                containerTemplate(name: 'mvn', image: 'maven', ttyEnabled: true, command: 'cat'),
        ],
) {
  podNode {
    ...      
  }
}
```

Or even a shortcut:

```
nodeFromPodTemplate(
        containers: [
                containerTemplate(name: 'mvn', image: 'maven', ttyEnabled: true, command: 'cat'),
        ],
) {
  
}
```

### CODE REVIEW

**Comment by carlossg** [comment]
@jglick is there a better way to achieve this than passing a variable ?

**Comment by marvinthepa** [comment]
@jglick any hints would be greatly appreciated...

**Comment by carlossg** [comment]
I think `podNode()` (step that extends Node step) with the same args as `podTemplate` could be the solution, but not a pipeline expert

**Comment by Vlatombe** [comment]
Done through #539 (since 1.17.0), the variable POD_LABEL can be used within `podTemplate` block.

**Comment by jglick** [comment]
Yes. This is similar to #539. I am afraid I never saw this PR.

**Pull request closed without merging**
