### PR TITLE
[JENKINS-35246] Test that Jenkins nodes are deleted after agent disconnection

### PR DESCRIPTION
**Pull request by carlossg**
https://issues.jenkins-ci.org/browse/JENKINS-35246

### CODE REVIEW

**Comment by carlossg** [comment]
Couldn't make the tests fail on minikube, will need to try on a real cluster, when #208 is merged

**Comment by marvinthepa** [comment]
I guess you are not trying to get rid of this exception with this pr?:

```
Computer.threadPoolForRemoting [#7] for pod-test-0001-1ls04-v28xw terminated
java.nio.channels.ClosedChannelException
	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:208)
	at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecvClosed(ApplicationLayer.java:222)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:832)
	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:287)
```

Because that one is still in the logs.

Also note that `SlaveComputer.disconnect` actually closes the connection asynchronously, so it might make sense to wait for the returned Future before continuing..

**Comment by carlossg** [comment]
You are right, let's try waiting for a bit

**Comment by marvinthepa** [comment]
I actually meant calling `wait` on the `Future` that is returned by `Computer.disconnect`.

But I tried that, and it doesn't get rid of the exception. As that is just a warning anyway, it's probably not a problem...

**Comment by carlossg** [comment]
`wait` is not what you think it is, it's `Object.wait`
`get` should wait for the disconnection to be finished

**Comment by carlossg** [comment]
it's not a problem, just trying to gracefully end connection and avoid stacktraces in logs

**Comment by marvinthepa** [comment]
> wait is not what you think it is, it's Object.wait
get should wait for the disconnection to be finished

Sorry, that is what I meant. I was experimenting with `get`, but it didn't help with the exception.

**Comment by carlossg** [comment]
Rebased on top of #248

**Comment by carlossg** [comment]
rebased

**Comment by Vlatombe** [comment]
Stale

**Pull request closed without merging**
