### PR TITLE
Add supplemental groups support to PodTemplates

### PR DESCRIPTION
**Pull request by zackmeath**

### CODE REVIEW

**Comment by Vlatombe** [comment]
Hi @zackmeath, do you know you can use the `yaml` field to specify all these extra attributes?

**Comment by zackmeath** [comment]
Yes, but we find it easier to manage the fields themselves using config-as-code. I suppose we could look into configuring the `yaml` to define every field, but we would like to avoid doing both as we have run into issues in the past where the two conflict.

**Comment by Vlatombe** [comment]
Needs a unit test

**Comment by zackmeath** [comment]
I added supplemental groups to some pre-existing tests

**Comment by zackmeath** [comment]
Hi @Vlatombe is there anything stopping this from going through?

**Comment by Vlatombe** [comment]
@zackmeath No, just lacking time to update the plugin lately. I'll be doing a new round soon.

**Comment by zackmeath** [comment]
Added support for KubernetesDeclarativeAgent

**Pull request merged**
