### PR TITLE
Use git plugin beta and git client beta - DO NOT MERGE

### PR DESCRIPTION
**Pull request by MarkEWaite**
Update dependency versions to use latest git plugin beta and latest git client plugin beta.

That update required an update of the apache-httpcomponents-client-4-api and the scm-api.

Exploring https://issues.jenkins-ci.org/browse/JENKINS-55387

**DO NOT MERGE**

### CODE REVIEW

**Comment by carlossg** [comment]
There was a glitch in CI, trying again with the beta plugins

**Comment by carlossg** [comment]
I guess the issue is git-client beta with git non beta

**Comment by MarkEWaite** [comment]
I tried that combination as well @carlossg.  I think I saw the same results.  Now that the checks are passing with the baseline, I'll mutate this pull request in a few different ways to learn more.

Thanks for reporting the problem and thanks especially for having an environment where the problem can be evaluated!

**Comment by MarkEWaite** [comment]
The git plugin 4.0.0-beta4 and git client plugin 3.0.0-beta6 versions pass all the integration tests when combined with the necessary scm api plugin 2.3.0 release and the necessary apache http components latest release.  Thanks for checking the latest beta releases of those plugins!

**Pull request closed without merging**
