### PR TITLE
Add token creation YAML for jenkins SA

### PR DESCRIPTION
**Pull request by Odilhao**
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did

While creating the basic SA for Jenkins to connect to one Kubernetes cluster that runs after [1.22](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-an-api-token-for-a-serviceaccount), it's necessary to create the Secret/Token.

### CODE REVIEW

**Comment by Vlatombe** [comment]
Hum... isn't the time-limited token enough in general?

**Comment by jglick** [comment]
> it's short limited in time

Right…but so what?

> You can still manually create a service account token Secret; for example, if you need a token that never expires.

What is the problem with the default behavior exactly?

**Comment by Odilhao** [comment]
> What is the problem with the default behavior exactly?

I don't see any problem, looking back now, I really think this should only be a documentation entry, explaining that a token I'll expiry in set amount of time and if it's necessary the user should create a long-lived API token.

**Comment by jglick** [comment]
> if it's necessary the user should create a long-lived API token

But why would it be necessary? What would the documentation explain?

If there is something in Jenkins which assumes that a service account token is permanently valid—so, reads it from disk and then caches it indefinitely without checking for new content—that would be a bug to fix, not something Jenkins administrators would be expected to work around by manually creating a long-lived token contrary to (current) K8s defaults and best practices.

**Comment by Vlatombe** [comment]
Closing as they're doesn't seem to be a motivation to introduce any change in the plugin.

**Pull request closed without merging**
