### PR TITLE
Add support for specifying per-container nvidia.com/gpu resource limit.

### PR DESCRIPTION
**Pull request by tnarg**

### CODE REVIEW

**Comment by carlossg** [comment]
Thanks for the PR but you can do this with the yaml syntax, precisely to avoid continuously needing new parameters 
Sorry for the extra work!

**Comment by tnarg** [comment]
I was unable to get this to work in the raw yaml. Mind providing an example?

**Comment by carlossg** [comment]
you just need to use the same yaml that you would use to launch the pod in k8s, with `nvidia.com/gpu` resource limit I assume

**Comment by therc** [comment]
The YAML approach isn't going to work right now, because `combine(Container, Container)` grabs explicitly only CPU and memory. I created #350 to remove the hardcoded resources. It works with CPU, memory, GPUs, extended resources (in the test, I'm using the same example resource as the Kubernetes docs) and also any future standard resources, such as local storage.

**Comment by markmssd** [comment]
Do you guys have an example of such a YAML? In my case, I'd like to add the `gpu` resource on the main `jnlp` container, so I'm trying to override the default pod template. I've tried with both the `override` and the `merge` strategies, but in vain.

```
  # Raw yaml template for the Pod. For example this allows usage of toleration for agent pods.
  # https://github.com/jenkinsci/kubernetes-plugin#using-yaml-to-define-pod-templates
  # https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  # yamlTemplate: ""
  yamlTemplate: |-
    apiVersion: v1
    kind: Pod
    spec:
      containers:
        - name: jnlp
           image: jnlp-image
           resources:
             requests:
               cpu: 1
               nvidia.com/gpu: 1
      tolerations:
        - key: "product"
          operator: "Equal"
          value: "jenkins"
          effect: "NoSchedule"
        - key: "nvidia.com/gpu"
          operator: "Equal"
          value: "present"
          effect: "NoSchedule"
```

**Pull request closed without merging**
