### PR TITLE
Fetch workspace from Master if all nodes are offline

### PR DESCRIPTION
**Pull request by alexpekurovsky**
Due to unknown destiny of original Pull Request (#142), I'm creating a new one with required fixes (https://github.com/jenkinsci/kubernetes-plugin/pull/142#discussion_r105837549)

### CODE REVIEW

**Comment by carlossg** [comment]
Based on https://github.com/jenkinsci/mesos-plugin/blob/master/src/main/java/org/jenkinsci/plugins/mesos/MesosWorkspaceBrowser.java#L15 does it need a shared filesystem, ie. NFS?

**Comment by alexpekurovsky** [comment]
As far as I understand original #142, how content of workspace will appear on master is out of scope of this code. It can be either copied by https://github.com/jenkinsci/copy-to-slave-plugin plugin or can be mounted as shared filesystem on both worker and master.

**Comment by carlossg** [comment]
LGTM but I don't know the inner details, asking for another review

**Comment by alexpekurovsky** [comment]
I will try to explain why this functionality is very important (not the code itself, but the idea):
Kubernetes plugin creates slave, runs job and destroys slave. Due to this fact workspace doesn’t exist anywhere after job finished. Here comes two problems:
- minor: you cannot browse workspace after job is finished
- major: Jenkins cannot determine SCM revision of last build and Poll SCM feature becomes totally useless - it rebuilds job every git polling. This means you can’t Build applications based on Poll SCM trigger on kubernetes slaves at all.

Current workaround we’re using is much uglier:
1. Use copy-to-slave plugin to copy workspace back to master
2. Run job once on master and switch back to label of kubernetes slave, so Jenkins will have a record in history about run on master and will check workspace on master

Am I missing anything?

**Comment by alexpekurovsky** [comment]
I think the idea of looping through Kubernetes Clouds and PodTemplates is based on fact that we need to understand if job was running through Kubernetes Slaves and we need to return workspace on master or not.
However I'm not sure, just trying to get somehow this functionality.

**Comment by alexpekurovsky** [comment]
@Vlatombe any progress here?

**Comment by Vlatombe** [comment]
> major: Jenkins cannot determine SCM revision of last build and Poll SCM feature becomes totally useless - it rebuilds job every git polling. This means you can’t Build applications based on Poll SCM trigger on kubernetes slaves at all.

This is a wrong statement. The git plugin is perfectly able to record what revision a build has used and to compare it with the latest revision available in the git repository without a workspace (that is, unless you use advanced options requiring a workspace).

I think the current PR could be applicable to the copy-to-slave plugin, but it has nothing to do in the kubernetes plugin (IMHO).

**Comment by alexpekurovsky** [comment]
Agree. Closing this PR.

**Comment by farahfa** [comment]
So is this not gonna happen? It would be very useful to debug jobs quickly by being able to access the workspace after the slave node is gone.

**Pull request closed without merging**
