### PR TITLE
Issue 1.  Fix prepending of erroneous /api/v1beta1 to test-connection HT...

### PR DESCRIPTION
**Pull request by ae6rt**
...TP GET

### CODE REVIEW

**Comment by carlossg** [comment]
I have committed the doc and the fix. Abut the new tests, I'm not sure starting a new stub server is a good idea, I think there should be only 2 types of tests:

* mock/stub classes, no http testing
* starting a kubernetes master server for testing (if possible)

**Comment by carlossg** [comment]
Thanks btw. I'm trying to cut a first release, but lacking permissions, hopefully soon will get that deployed to the update center

**Comment by ae6rt** [comment]
No problem on the embedded http server.  

Also, you can probably cherry-pick this commit that gives the jelly templates help icons that describe the fields the plugin has control of:

https://github.com/xoom/kubernetes-plugin/commit/18f4a7df351074a7ef9621d763924781b7f6074d

Feel free to decline this PR now that it's work is done.  The URL fix was sufficiently trivial that nothing will really be lost with the discarding of the embedded http server test.  In retrospect, I should have done this work on a different branch than my fork's master.  Live and learn.

**Comment by carlossg** [comment]
Can you create a new PR for 18f4a7d so it gets tracked? Easier for me to merge too

**Comment by ae6rt** [comment]
Done.



On Wed, Apr 15, 2015 at 8:44 AM, Carlos Sanchez <notifications@github.com>
wrote:

> Can you create a new PR for 18f4a7d
> <https://github.com/jenkinsci/kubernetes-plugin/commit/18f4a7df351074a7ef9621d763924781b7f6074d>
> so it gets tracked? Easier for me to merge too
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jenkinsci/kubernetes-plugin/pull/1#issuecomment-93455639>
> .
>



-- 
Mark

**Pull request closed without merging**
