### PR TITLE
Avoid pod garbage collection thread getting killed because of a common unhandled exception

### PR DESCRIPTION
**Pull request by Vlatombe**
### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by amuniz — APPROVED** [review]

**Comment by felipecrs** [comment]
Speaking of pod garbage collection, do you or someone else mind answering whether GC runs against the whole cluster or only against the namespace dedicated to the cloud?

The doc doesn't make this clear. I did not enable this feature fearing this.

image

Since we are talking about **deleting** resources, it would be nice to make this clearer.

**Comment by Vlatombe** [comment]
Hi, this is already part of the inline help if you enable the option.
Capture d’écran 2024-06-27 à 17 39 07

But we can probably pull up this inline doc to the section inline help if you find it more discoverable.

**Comment by felipecrs** [comment]
Oh. I never thought of enabling that option to see more docs.

Yeah, I think it would be nicer to mention that the cleanup is limited to the namespaces configured.

But this is no big deal. Don't worry.

Thanks a lot!

**Comment by sodul** [comment]
An other off topic question. If I want to reduce the frequency of the thread, would that be done though:
```
-Dorg.sanchez.jenkins.plugins.kubernetes.GarbageCollection.recurrencePeriod=300
```

**Comment by jglick** [comment]
(amending #1543 FTR)

**Pull request merged**
