### PR TITLE
JENKINS-46278: workaround code for providing environment variables to…

### PR DESCRIPTION
**Pull request by MattLud**
This fix allows a work around where you can use environment variables to be set in the container.

### CODE REVIEW

**Comment by scoheb** [comment]
Works well!
Tried with both `withEnv` and `env.SOME_VAR` in a standard pipeline (non-declarative).

**Comment by MattLud** [comment]
Should also work with `withCredentials` as well!

**Comment by ruebenramirez** [comment]
+1

**Comment by iocanel** [comment]
@MattLud @carlossg: If I am not mistaken, this will result in build pods inheriting the env vars of the jenkins master, which can be problematic in many cases (e.g. screwing up PATH, JAVA_HOME etc).

wdyt?

**Comment by iocanel** [comment]
I think that implicitly inheriting from jenkins master can be really dangerous. So, I'd like to counter propose to just take withEnv into consideration. I think we could easily implement that if we picked up the EnvExpander instead of the EnvVars from the context.

**Comment by iocanel** [comment]
See #206

**Comment by MattLud** [comment]
Agreed - #206 is better - Are there any docs on EnvironmentExpander somewhere?

**Pull request merged**
