### PR TITLE
[JENKINS-55960] Missing DeclarativePipeline podTemplate parameters

### PR DESCRIPTION
**Pull request by cazorla19**
All issue details here:

https://issues.jenkins-ci.org/browse/JENKINS-55960

Changeset:

1. Added `slaveConnectTimeout` and `namespace` to Declarative Pipeline class.

### CODE REVIEW

**Comment by cazorla19** [comment]
@carlossg any update on this issue? It's blocking us as a plugin users, so I'd like to have any feedback

**Comment by marshallford** [comment]
How does the `slaveConnectTimeout` parameter relate to the system property `org.csanchez.jenkins.plugins.kubernetes.PodTemplate.connectionTimeout` and [agent connection timeout instructions](https://github.com/jenkinsci/kubernetes-plugin#specifying-a-different-default-agent-connection-timeout) in the readme?

**Comment by carlossg** [comment]
`org.csanchez.jenkins.plugins.kubernetes.PodTemplate.connectionTimeout` is the default if you don't set `slaveConnectTimeout`

**Comment by marshallford** [comment]
I am getting following error when setting `
slaveConnectTimeout` to 6000 (100 minutes) after ~21 minutes. Is this parameter related to the error?

```
Cannot contact jenkins-worker-88405759-c90a-47a9-89b3-a1c368fd64d4-q6sfl-bss5r: hudson.remoting.ChannelClosedException: Channel "unknown": Remote call on JNLP4-connect connection from 10.8.35.7/10.8.35.7:57044 failed. The channel is closing down or has closed down
```

**Comment by carlossg** [comment]
if you can ask in the jenkins-users mailing list with more details

**Comment by marshallford** [comment]
@carlossg Any chance #442 is related to the issue I described above?

**Pull request merged**
