### PR TITLE
[JENKINS-39867] Upgrade fabric8 to 1.4.26

### PR DESCRIPTION
**Pull request by carlossg**
Fixes Unauthorized message from OpenShift API

### CODE REVIEW

**Comment by carlossg** [comment]
I haven't tested it yet, other than just compiling ok without errors

**Comment by iocanel** [comment]
@carlossg: It's a long story, but this actually saves me from hours of troubleshooting :-)

It looks great and I will try it asap!

**Comment by iocanel** [comment]
@carlossg: I think that after this, its a good time for a release, wdyt?

**Comment by dserodio** [comment]
Yes, please make a new release. I tried testing this PR locally with `mvn hpi:run` but I get a nasty `java.lang.LinkageError: Failed to load jenkins.util.SystemProperties` error which I'd rather not try to debug :)

**Pull request merged**
