### PR TITLE
Make it possible to define more than one containers inside a pod.

### PR DESCRIPTION
**Pull request by iocanel**
Using multiple containers inside a pod, opens the way to some very interesting possibilities, like using sidecar containers etc. 

So for example we could create a pod that consists of a jnlp container, plus a container with the build tool of our choice.  

My intention is to use this feature as a base and add pipeline capabilities on top of that for executing shell commands in the container of our choice etc.

### CODE REVIEW

**Comment by carlossg** [comment]
Awesome, thanks!
After a quick look, what are the chances that backwards compatibility could be kept?
classes would need to be deprecated instead of deleted, but could create a pod with only one container if the config comes from the previous version?

**Comment by iocanel** [comment]
Well if we don't mind having redudant stuff (e.g. image, env, commands both on pod and on container) I don't really mind, meaning that I would gladly work on it asap.

Can you think of an other way?

**Comment by carlossg** [comment]
maybe all the public methods in PodTemplate that are gone could just stay deprecated and operate on the first container of the Pod

**Comment by iocanel** [comment]
Will that cover porting old configs to the new version?

**Comment by iocanel** [comment]
TBH, I prefer having redudant fields than operate on the first container, as the later can get messy..

**Comment by carlossg** [comment]
configuration migration is typically done in `DescriptorImpl.readResolve`, not a big expert on that myself but I think that's where the stored config can be converted

**Comment by sdouche** [comment]
Is it really useful to accept the old format? Be able to specify a multiple containers is a big step forward. The tradeoff seems good.

**Comment by iocanel** [comment]
Well, from my point of view, the only reason to be backwards compatible is to allow users upgrade to the new version without breaking them.

**Comment by sdouche** [comment]
The pod specification needed for the mono container pod is very easy. Giving an example is imho enough.

**Comment by iocanel** [comment]
I've updated the PR, the old config now works properly and now I don't think that we break compatibility in any other way.

**Comment by sdouche** [comment]
Great @iocanel. Is it possible to download somewhere your build to test on my local cluster? I'm not a Java developer but I'll happy to test it.

**Comment by iocanel** [comment]
@sdouche: I'll try to upload a build on my dropbox and share :-)

**Comment by iocanel** [comment]
Added a few more commits that do the following:
- Introduce a pipeline step that allows you to select which container to use for all 'sh' steps.
- Add support for pseudo-TTY.
- Fix arguments (which were always appending jnlpmac and computer name). Now they don't but user can use ${computer.jnlpmac} ${computer.name} explicitly. Implemented in a backwards compatible way (without breaking existing users).

**Comment by sdouche** [comment]
Hi @iocanel. I'm ready for testing, how to get a build of your version?

**Comment by iocanel** [comment]
@sdouche: as promised: https://dl.dropboxusercontent.com/u/14547746/kubernetes.hpi

The build also contains the pipeline step to execute sh commands in the pod of your choice.

**Comment by sdouche** [comment]
@iocanel Is it possible to read somewhere the configuration (yaml?) produced by the plugin?

**Comment by iocanel** [comment]
Yes, all the old fields are retained for compatibility reasons. If not ContainerTemplate is defined,  we create one based on what's found in the PodTemplate.

Now regarding, the yaml I am not sure I get the question.

**Comment by sdouche** [comment]
> Now regarding, the yaml I am not sure I get the question.

The goal is to know easily what configuration is sent to the cluster.

**Comment by sdouche** [comment]
@iocanel can you give me a working example (with basic docker images on the hub) to be sure I understand correctly how work the plugin?

**Comment by iocanel** [comment]
Added a new pipeline step which allows you to easily define or override a pod template from within the DSL.  So one could directly configure and use the kubernetes-plugin from the pipeline without having to set up anything up front. Here's an example:

    podTemplate(label: 'mypod', containers: [[name: 'builder', image: 'maven'], 
                             [name: 'jnlp', image: 'fabric8/jenkins-jnlp-client:latest', command:     '/usr/local/bin/start.sh', args: '${computer.jnlpmac} ${computer.name}', ttyEnabled: false]]]) {

      node ('mypod') {
       git 'https://github.com/fabric8io/kubernetes-client.git'
       container(name: 'builder') {
          sh 'mvn clean install'
       }
      }
    }

@sdouche: You can use the snippet above as a pipeline script in a project of type pipeline and use the latest version of the plugin from my dropbox.

**Comment by sdouche** [comment]
@iocanel typo in your script (s/false]]]/false]]).

Tested on Jenkins 2.7.1 (installation from scratch):
```
Started by user admin
[Pipeline] podTemplate
[Pipeline] {
[Pipeline] node
Still waiting to schedule task
kubernetes-923b2c5bdfa141c188221568e47fe650-8763edc7ab0b is offline
Running on kubernetes-923b2c5bdfa141c188221568e47fe650-8763edc7ab0b in /home/jenkins/workspace/test2
[Pipeline] {
[Pipeline] git
Cloning the remote Git repository
Cloning repository https://github.com/fabric8io/kubernetes-client.git
 > git init /home/jenkins/workspace/test2 # timeout=10
Fetching upstream changes from https://github.com/fabric8io/kubernetes-client.git
 > git --version # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/fabric8io/kubernetes-client.git +refs/heads/*:refs/remotes/origin/*
 > git config remote.origin.url https://github.com/fabric8io/kubernetes-client.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/fabric8io/kubernetes-client.git # timeout=10
Fetching upstream changes from https://github.com/fabric8io/kubernetes-client.git
 > git -c core.askpass=true fetch --tags --progress https://github.com/fabric8io/kubernetes-client.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision 16f0261a1f17e016991f6942fb0faa4779869172 (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 16f0261a1f17e016991f6942fb0faa4779869172 # timeout=10
 > git branch -a -v --no-abbrev # timeout=10
 > git checkout -b master 16f0261a1f17e016991f6942fb0faa4779869172
First time build. Skipping changelog.
[Pipeline] container
[Pipeline] {
[Pipeline] sh
[test2] Running shell script
Executing shell script inside container: [builder] of pod: [kubernetes-923b2c5bdfa141c188221568e47fe650-8763edc7ab0b]
java.net.UnknownHostException: kubernetes.default.svc: unknown error
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at com.squareup.okhttp.Dns$1.lookup(Dns.java:39)
	at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:175)
	at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:141)
	at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:83)
	at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
	at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
	at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
	at com.squareup.okhttp.Call.getResponse(Call.java:286)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
	at com.squareup.okhttp.Call.access$100(Call.java:35)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:171)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline
java.io.IOException: Pipe not connected
	at java.io.PipedOutputStream.write(PipedOutputStream.java:140)
	at java.io.OutputStream.write(OutputStream.java:75)
	at org.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecDecorator$1.launch(ContainerExecDecorator.java:102)
	at hudson.Launcher$ProcStarter.start(Launcher.java:381)
	at org.jenkinsci.plugins.durabletask.BourneShellScript.launchWithCookie(BourneShellScript.java:147)
	at org.jenkinsci.plugins.durabletask.FileMonitoringTask.launch(FileMonitoringTask.java:61)
	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.start(DurableTaskStep.java:158)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:157)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:117)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:117)
	at groovy.lang.GroovyObject$invokeMethod.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:151)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:21)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:115)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:149)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:146)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:123)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:123)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:123)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:15)
	at WorkflowScript.run(WorkflowScript:12)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:55)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:106)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:58)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:154)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:32)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:29)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:108)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:29)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:164)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:360)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$100(CpsThreadGroup.java:80)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:236)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:226)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:47)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Finished: FAILURE
```

**Comment by sdouche** [comment]
Another point: I can't remove the default option and let the field empty. Ex: I don't want to override the entrypoint but the field `Command to run slave agent` is on `sh '-c`.

**Comment by carlossg** [comment]
I have created a `pod` branch with the commits from here, but it seems to be a lot to digest. It would be good to split the pipeline work into its own PR

**Comment by iocanel** [comment]
@carlossg:  TBH each of the commits included in this PR could be a PR on its own. I used a single PR for all of those commits, since the pipeline stuff depend on the pod template refactoring. If you'd like to treat them specially let's remove the pipeline steps from this PR and I'll create a new one once this is merged.

**Comment by carlossg** [comment]
ok, I have created a pod branch for the multi-container work and a pipeline branch that has all commits. Both are rebased with conflicts solved
I'll be taking a look at the pod branch asap.

**Comment by carlossg** [comment]
Please check #67 and #68 for the updated PRs

**Comment by carlossg** [comment]
and thanks!

**Pull request closed without merging**
