### PR TITLE
The pod watcher now checks readiness of the right pod.

### PR DESCRIPTION
**Pull request by iocanel**

### CODE REVIEW

**Comment by JeanMertz** [comment]
This solves the issue I described in https://github.com/jenkinsci/kubernetes-plugin/pull/95#issuecomment-264146794

👍

**Comment by iocanel** [comment]
@carlossg: So, do we review everything, or simple commit like this can go in directly?

**Comment by carlossg** [comment]
we can use github PR review for now

**Comment by JeanMertz** [comment]
While we're at it, quick question:

Does Jenkins/the community require that issues are reported through Jira, or can GitHub Issues also be enabled on this repository?

Just asking, because I'm not really a fan of Jira and to me it feels like an extra barrier compared to GitHub issues, but I can understand that it makes global ticket/issue management of all things Jenkins a lot easier if it's all combined in one system.

**Comment by carlossg** [comment]
They should go through Jira

**Pull request merged**
