### PR TITLE
archive artifact and findbugs findings

### PR DESCRIPTION
**Pull request by marvinthepa**
Archive artifacts so that users can more easily check if a certain pull request solves their problem.

Archive findbugs findings to easier find your violations.

### CODE REVIEW

**Comment by marvinthepa** [comment]
@carlossg : could you install the findbugs plugin on https://jenkins.gke.csanchez.org?

Or should I remove the findbugs archiving?

**Comment by carlossg** [comment]
the artifacts are already archived in https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fkubernetes-plugin/detail/archive_artifact_and_findbugs/2/artifacts

**Comment by marvinthepa** [comment]
@carlossg: I didn't know that https://ci.jenkins.io was still building the pull requests as well.

Sometimes the pull requests link to https://ci.jenkins.io, some link to https://jenkins.gke.csanchez.org. Could we have them link to both?

**Comment by carlossg** [comment]
I don't know how to configure it right now,  being both jenkins seems that the latest just overwrites the previous one

**Pull request merged**
