### PR TITLE
CI with travis for pre-releases

### PR DESCRIPTION
**Pull request by ReSearchITEng**
there are no builds for snapshots, and releases are only every few months.
This is a template from the .travis.yml which was tested and works.
I warmly suggest you will accept it, add the relevant secured oauth key, and allow us to have a build every time there is a commit.

### CODE REVIEW

**Comment by carlossg** [comment]
there are indeed builds for each commit and PRs, ie.
https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fkubernetes-plugin/detail/master/32/artifacts

**Comment by ReSearchITEng** [comment]
Oh, I googled internet up and down, could not find them and did this link anywhere...
Could you also upload the build of these snapshots as pre-releases in github ?

**Comment by marvinthepa** [comment]
@carlossg should we close this?

**Comment by carlossg** [comment]
I don't think it makes sense to have pre-releases in github as anyone can download from the above link

**Pull request closed without merging**
