### PR TITLE
[JENKINS-50429] Shell commands too slow

### PR DESCRIPTION
**Pull request by fabricepipart1a**
This Pull Request is a fix proposal for [JENKINS-50429](https://issues.jenkins-ci.org/browse/JENKINS-50429
)
### Issue summary

When running the following script, the sh commands ran inside the container are slowed down:
```
podTemplate(label: label) {
  node(label){ 
      stage('20 calls outside container'){
          for (i = 0; i <20; i++) {
              sh "date"
          }
      }
      stage('20 calls inside container'){
          container("jnlp"){
              for (i = 0; i <20; i++) {
                  sh "date"
              }
          }
      }
  }
}
```

The results are usually:
Outside container: ~12 seconds
Inside container: ~1min 10 seconds

### Issue root cause

We have isolated the cause of the slowdown to the 1s wait in java.io.PipedOutputStream's write() method. The symptom being that whenever the process tries to write to the buffer (namely all the export environment variable statements), a number of the write() calls will block for 1+ seconds due to the buffer being full. 

This is explained [here](https://stackoverflow.com/questions/28617175/did-i-find-a-bug-in-java-io-pipedinputstream), [here](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8014239) and [here](https://bugs.openjdk.java.net/browse/JDK-8014239)

### Issue fix proposal

The fix ideas came from [this issue on kubernetes-client](https://github.com/fabric8io/kubernetes-client/issues/1008).

There are two options for the fix, instantiating another `PipedOutputStream` and using reflection to set the buffer size.

#### Instantiating another `PipedOutputStream`
This is one solution proposed in Dec 2018 in [the kubernetes-client issue mentioned above](https://github.com/fabric8io/kubernetes-client/issues/1008).
```
        PipedInputStream pipedInputStream = new PipedInputStream(1024 * 1024);  // pipeSize is 1m
        PipedOutputStream pipedOutputStream = new PipedOutputStream(pipedInputStream);
```
In our case that requires to replace `redirectingInput()` as found [here](https://github.com/jenkinsci/kubernetes-plugin/blob/master/src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java#L281-L283) , which does `writingInput(new PipedOutputStream())` ([see here](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodOperationsImpl.java#L286-L288)) by a call to `writingInput(pipedOutputStream)` with a `PipedOutputStream` that we would have built ourselves with a custom buffer size.

The problem I faced was that `new PipedOutputStream(pipedInputStream)` and `new PipedOutputStream()` behave slightly differently. One calls an internal method `connect` (see [here](https://github.com/karianna/jdk8_tl/blob/master/jdk/src/share/classes/java/io/PipedOutputStream.java#L63-L76)) and one does not.
Unfortunately, it seems that the plugin code calls explicitly the `connect` method [in ExecWebSocketListener](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ExecWebSocketListener.java#L183-L209). As a consequence, I did not work.

Honestly, it could probably work, but I did not manage to make it work this way. Or it would have required too many changes.

#### Using reflection to set the buffer size

Since the issue is the related to the buffer size of the `PipedOutputStream`, an option is to try to modify the buffer size via reflection since it is not explicitly configurable.
This is the fix done here that has the defect of using reflection but the advantage of being concise in order to workaround this JDK "bug".

Please note that the buffer size I set is not really justified. I am open to any suggestion to adjust the size.

### Results

With the fix proposed, the pipeline mentioned at the beginning went from 1min47 sec to 8s.

### CODE REVIEW

**Comment by carlossg** [comment]
Thanks for the investigation!

To do the proper fix, instantiating another `PipedOutputStream`, this could be done in the `kubernetes-client` project?

**Comment by fabricepipart1a** [comment]
To do a fix that would not require any reflection, I have the impression (I am unsure honestly) that it would require a change in https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ExecWebSocketListener.java#L183-L209
I really don't feel confident to do so as I am unsure what would be the consequences (aere there other `PipedOutputStream` created with the same pattern?).

**Comment by mrjgreen** [comment]
@fabricepipart1a - the issue you referenced fabric8io/kubernetes-client#1008 looks a little stale. I wonder if we can do anything to get it moving again... @carlossg, I'm not familiar enough with the fabricate library to know where to start with a PR - do you have any sense of where the best place to apply this change might be? If you can point us in the right direction I'd be happy to try and get something into that lib.

**Comment by pyieh** [comment]
Do you know if this change could cause issues due to the sink essentially being replaced with a different buffer? Because there are previous calls to the PipedOutputStream.write() and if the contents haven't been completely flushed/read by the reader, then the data will be lost when you replace it with this new buffer.

**Comment by fabricepipart1a** [comment]
I thought I had placed the code before any write. Indeed if I did not, it needs to be changed. Let me do that immediately!

**Comment by carlossg** [comment]
Thanks for all the pointers! I think I got the right fix without reflection at #427

**Pull request closed without merging**
