### PR TITLE
[WiP] use auto generated swagger client

### PR DESCRIPTION
**Pull request by ndeloof**
currently blocked by https://github.com/swagger-api/swagger-codegen/issues/1066

### CODE REVIEW

**Comment by elibixby** [comment]
@ndeloof @carlossg This will also require significant code changes to bring the plugin up to date with the k8s v1 API, since that is the only swagger spec available.

**Comment by carlossg** [comment]
the plugin already works with v1

**Comment by ndeloof** [comment]
@elibixby plugin already uses v1 API (based on fabric8 client), so I don't think this would be such a pain to migrate.

**Comment by elibixby** [comment]
@ndeloof My mistake didn't see that you migrated from https://github.com/carlossg/KubernetesAPIJavaClient to the fabric8 client.

**Pull request closed without merging**
