### PR TITLE
[JENKINS-61931] Add ability to set docker registry prefix for default JNLP image

### PR DESCRIPTION
**Pull request by narayanan**
For security reasons most enterprises mandates all docker image pulls are proxied through enterprise docker registry. Prior to this change, only possible mechanism will be to set the entire image with proxy prefix as system property. Though it works, it comes with huge maintenance overhead as the property value needs to be frequently changed to use newer version of inbound agents. This change allows to set the docker registry prefix once and inherit the default JNLP image defined in the ode.

- Fixes [JENKINS-61931](https://issues.jenkins-ci.org/browse/JENKINS-61931).
- Added ability to set docker registry prefix for default JNLP image using System Property

Looks like its not possible to test this change via unit tests, hence tested locally to ensure the changes work.

### CODE REVIEW

**Comment by narayanan** [comment]
Not sure why the unit tests failed in the `kind` branch... unit tests passed in `jdk11` branch.

**Comment by Vlatombe** [comment]
Could you add a unit test for this asserting the image in the pod spec uses the prefix provided through system properties?

The failure on `KubernetesPipelineTest#podTemplateWithMultipleLabels` is a known flake, so it is fine.

**Review by Vlatombe — COMMENTED** [review]
Could you add a unit test for this asserting the image in the pod spec uses the prefix provided through system properties?

The failure on `KubernetesPipelineTest#podTemplateWithMultipleLabels` is a known flake, so it is fine.

**Comment by narayanan** [comment]
I can add a unit test, but how do I set a system property for just one unit
test and not set for others?

**Comment by Vlatombe** [comment]
@narayanan remove the `final` on the field and set it at the beginning of the test. You can use `@FlagRule` to help you do that.

**Comment by narayanan** [comment]
@Vlatombe Added unit tests.

**Pull request merged**
