### PR TITLE
[JENKINS-40457] java.lang.ArrayStoreException when a image pull secret is defined

### PR DESCRIPTION
**Pull request by carlossg**
Use the correct type

### CODE REVIEW

**Comment by moserke** [comment]
When will this be released as a new version?  Having this same issue and can not use the plugin because we require image pull secrets

**Comment by pashok2398** [comment]
Hi Team,
Any estimated release date?
Thanks

**Comment by carlossg** [comment]
soon :)

if anyone wants to test https://issues.jenkins-ci.org/browse/JENKINS-40960 first it would help

**Comment by eggsy84** [comment]
Sure thing I'll give that a test today

**Pull request merged**
