### PR TITLE
Read the content of bearer token from secrets

### PR DESCRIPTION
**Pull request by mfojtik**
This will read the content of service account from container (if exists). So there is no need to supply any credentials.

### CODE REVIEW

**Comment by mfojtik** [comment]
@ndeloof FYI

**Comment by ndeloof** [comment]
I'm not a fan of this, this relies on system way to pass credentials, if we want to go this way then this should be proposed as an improvement in credentials plugin. @carlossg wdyt ?

**Comment by mfojtik** [comment]
@ndeloof the problem I'm trying to solve is to bootstrap the Jenkins running in Kubernetes automatically without the need of manual configuration... If there is a way to import the bearer token to credentials plugin from a shell script I'm happy to use that :-)

**Comment by ndeloof** [comment]
You can use a groovy script on init for this purpose, using credentials plugin API to create the required item. But don't make me wrong, assuming `/var/run/secrets/` is a recommended solution on Linux, it would make sense credentials plugin do support it as well. @ydubreuil wdyt ?

**Comment by mfojtik** [comment]
@ndeloof it is the default path Kubernetes (or OpenShift) mounts the secrets AFAIK

**Comment by ndeloof** [comment]
right, so this is very specific to this type of deployments. 
then a groovy script to pick up this file content and setup the credentials would solve your issue

**Comment by mfojtik** [comment]
@ndeloof well, this is a 'kubernetes' plugin and this is specific to kubernetes. I don't really love the idea to need to write a groovy script to populate the credentials plugin if we can read the token straight from the disk.

**Comment by akostadinov** [comment]
What about a configuration option to read token from local file. That would be pretty useful for a lot of deployments. Or a native oerating system command to read token.

I can't imagine how this could be handled by the credentials plug-in. You mean to create a new type of credentials? Could you explain?

**Comment by ndeloof** [comment]
@mfojtik right, but using kubernetes to host the build isn't the same as being hosted on kubernetes :P

**Comment by ndeloof** [comment]
so :+0:

**Comment by bparees** [comment]
@ndeloof true, but it seems likely someone running their slaves on k8s would be running the master on k8s.

**Comment by mfojtik** [comment]
Also if you set the credentials, reading the token is skipped entirely + if the token does not exists, this will just print warnings (which I think I can just remove or move to higher debugging level). So this will work for you only if you run master on kubernetes AND you don't configure any credentials.

**Comment by ndeloof** [comment]
I leave this decision to @carlossg who has better experience with hosting jenkins on k8s

**Comment by ndeloof** [comment]
@mfojtik can you please provide a link to openshit/kubernetes documentation about this `/var/run/secrets/` path ? I wonder we could declare a specific credential implementation for this use-case, you could create once and select on cloud config, and would then be portable across kubernetes deployments.

**Comment by mfojtik** [comment]
@ndeloof i was not able to find any docs, but this is the source where this is implemented: https://github.com/kubernetes/kubernetes/blob/e8f77b3673e5032342615a13afd2deac60b2c537/plugin/pkg/admission/serviceaccount/admission.go#L44

Also I found blog about Jenkins & Kubernetes that also use this token: http://iocanel.blogspot.cz/2015/09/jenkins-setups-for-kubernetes-and.html

I think it would be sufficient to have something like "get credential from env var" and then I can just setup `KUBERNETES_TOKEN_PATH` or something and the credential will be picked up. Does Jenkins credentials plugin have something like that?

**Comment by ndeloof** [comment]
Would you think https://github.com/ndeloof/kubernetes-plugin/commit/f190b5567f2704f92b2d61d7e105c63fb94babba would be a valid approach ?

This one adds a new credentials type you can statically configure with your jenkins config template.

**Comment by mfojtik** [comment]
@ndeloof yes, I think that might work :+1:

**Pull request closed without merging**
