### PR TITLE
Add support for yamlMergeStrategy in declarative pipelines

### PR DESCRIPTION
**Pull request by nlebas**
Allows to merge yaml with inherited templates like this:

```
pipeline {
  agent {
    kubernetes {
      inheritFrom "test-template"
      yamlMergeStrategy merge()
      yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: maven
    image: maven:3.3.9-jdk-8-alpine
    command: ['cat']
    tty: true
"""
    }
  }
  stages {
    stage('Run maven') {
      steps {
        container('maven') {
          sh 'mvn -version'
        }
      }
    }
  }
}
```

### CODE REVIEW

**Comment by hkrpavan** [comment]
@nlebas , Can i merge two yamlFiles? If so do you have sample code?

**Comment by nlebas** [comment]
@hkrpavan , I didn't test yamlFile, I personally do not have a use case for it.

But looking at the code I would guess that yamlFile is simply ignored by the declarative pipeline syntax, with or without inheritance.

I guess you can try adding it to the getAsArgs method and make a pull request if it works for you.

**Comment by hkrpavan** [comment]
@nlebas, Thank you for your reply. Let me check the code in getAsArgs.

**Comment by hkrpavan** [comment]
One final question. Can we define podTemplate in a shared library for declarative pipelines with out using jenkins config?

**Comment by nlebas** [comment]
I don't know. I do exactly that and so far it suits my needs.

**Comment by hkrpavan** [comment]
Ok. Thank you.

**Comment by skalaiyarasan** [comment]
@hkrpavan have you get that how to merge two yaml files?

**Comment by hkrpavan** [comment]
@skalaiyarasan , nope I am not merging two yams files. Instead using a parent pod template in Jenkins configuration to merge with an yams file.

**Pull request merged**
