### PR TITLE
Give more time to agent to reconnect after a restart in CI

### PR DESCRIPTION
**Pull request by Vlatombe**
15 seconds look too short for CI -- https://github.com/jenkinsci/workflow-durable-task-step-plugin/blob/019404b3832a42a312766384d437162bcb93aeed/src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java#LL95C84-L95C166

- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by dduportal** [comment]
nitpick question: is this value tunable by an administrator?

**Comment by Vlatombe** [comment]
You mean, for a production system?

**Comment by jglick** [comment]
The production default is 5m. 15s is the default in tests.

**Comment by dduportal** [comment]
Oh I see, sorry for the noise. I mis-read the PR change. Thanks for the explanation and the work!

**Pull request merged**
