### PR TITLE
Add example Jenkins file integrating k8 Resources API

### PR DESCRIPTION
**Pull request by LarsOL**
After a bit of hair pulling, this seems to be the answer to deploying the container on large machines.

We had the issue that by default the JVM wants to take 1/4 of the total RAM, which on a 32gb machine is overkill. But the JVM is not aware of kubernetes limits, and would be OOM killed. 

This works, but we still have the issue that RAM (I believe the non-heap) grows with time until it hits the k8 limit. It seems to be cache RAM in that it doesn't crash the app when reaching the limit like the heap did.

Any help would be appreciated.

### CODE REVIEW

**Comment by carlossg** [comment]
This is a typical problem with docker and jvm. Off-heap memory shouldn't grow without control, it depends on what plugins are installed or what are you doing in jenkins.

I think it makes sense to merge this into `gke.yml`

**Comment by LarsOL** [comment]
Yeh I thought i was weird too, our jenkins instance only uses native jenkins pipelines (Minimal subset of default plugins + bitbucket-branch-source). So i don't know what could be happening.

On a side note, I noticed that the gke.yml uses jenkins image directly now. Does that mean the Dockerfile and csanchez/jenkins-kubernetes:latest is deprecated?

**Comment by carlossg** [comment]
> I noticed that the gke.yml uses jenkins image directly now. Does that mean the Dockerfile and csanchez/jenkins-kubernetes:latest is deprecated?

csanchez/jenkins-kubernetes is based on jenkins image + this plugin, should still be valid

**Comment by rhuss** [comment]
fwiw and just in case you need some sensible defaults for a heap memory limit, we settled on using 50% of the available memory for -Xmx. That turned out to work quite well up to now. We tried with 80% that was too much (and we run in OOM, too)

You can refer to [this script](https://github.com/fabric8io-images/run-java-sh/blob/master/fish-pepper/run-java-sh/fp-files/container-limits) for how the limits and the available cores are detected with from within a container. Here's [the code](https://github.com/fabric8io-images/run-java-sh/blob/master/fish-pepper/run-java-sh/fp-files/container-limits#L39-L50) for setting `-Xmx` based on these limits. 

I can also recommend these useful presentations which discussion the issue of Java resource management within containers quite extensively:

* https://youtu.be/Vt4G-pHXfs4
* https://www.youtube.com/watch?v=w1rZOY5gbvk
* https://vimeo.com/album/4133413/video/181900266

**Comment by LarsOL** [comment]
To be honest that was what I was trying to avoid, we had two jenkins instances + other servers running happily on a 1vcpu, 3.6gb machine. But now that we have 20gb nodes, it seems ridiculous and inefficient  to require 10gb per instance. 

And thank you for the links, I'll look into them.

**Comment by rhuss** [comment]
@LarsOL With 50% I don't mean 50% of the available node memory but 50% of the memory limit that you have configured for your pods.

**Comment by LarsOL** [comment]
Ah, sorry for the misunderstanding. 
Yeh thats what we settled on too, as seen in the PR

**Comment by rhuss** [comment]
yeah, correct. Just wanted to point out yet another solution, which could work completely opaque without setting environment variables from the outside (by detecting the limit directly from the startup script by querying some resources from the /proc filesystem).

**Comment by LarsOL** [comment]
@carlossg btw I have merged into a single gke.yml

**Pull request merged**
