### PR TITLE
Any Secret File credential can be be used for any kubeconfig, not just AKS

### PR DESCRIPTION
**Pull request by rodrigc**

### CODE REVIEW

**Comment by rodrigc** [comment]
@markyjackson-taulia

**Comment by rodrigc** [comment]
@markyjackson-taulia talking to you was A++

**Comment by rodrigc** [comment]
As we discussed, I think it would be super helpful to refactor the README of this plugin to accomodate a workflow such as:

1.  Create a Kubernetes cluster somehow, somewhere
2.  Obtain a Kubeconfig file from 1.
3.  Create a Jenkins Credential Secret File from 2.
4.  Start using the kubernetes-plugin against the cluster created in 1.


I work with a lot of different types of Kubernetes clusters such as:
* on-prem created by Kubespray
* provisioned in EKS via eksctl
* provisioned in PKS via pks
* created in AKS via aks

The one commonality between all types of clusters is that they give you a kubeconfig file.

**Comment by markyjackson-taulia** [comment]
I agree. I am adding this to a roadmap and will work on this over the next few days. I will tag you for a review

**Comment by markyjackson-taulia** [comment]
That may be good.

**Pull request merged**
