### PR TITLE
Use `kubernetes.io/os` as OS node selector now that 1.14 is the oldest supported.

### PR DESCRIPTION
**Pull request by Vlatombe**

### CODE REVIEW

**Comment by mbarbero** [comment]
What do you mean by "1.14 is the oldest supported"? I can't find any reference about minimumn required k8s version. What's the current status?

**Comment by Vlatombe** [comment]
@mbarbero Kubernetes 1.14 is the oldest version supported by most Kubernetes providers. The kubernetes plugin is following the same trend.

On OpenShift side I know 3.11 is still supported by RedHat and is based on Kubernetes 1.11, but for this configuration it is possible to set the node selector explicitly to `beta.kubernetes.io/os=linux`. I can add that to release notes + OpenShift section to clarify.

**Comment by mbarbero** [comment]
Thanks for the swift reply. 

I think that the minimum supported versions for both openshift and vanilla kubernetes should be listed explicitly on the README, just to manage expectations. Thanks!

**Comment by Vlatombe** [comment]
@mbarbero I'll add it. Thanks for your feedback!

**Comment by autarchprinceps** [comment]
Always specifying at least one node selector breaks the scale from 0 capability of Kubernetes Cluster Autoscaler. Is there some way to forcibly override this default set? Given that you explicitly force it on here, if it is either empty or explicitly null

**Comment by Vlatombe** [comment]
@autarchprinceps it depends on your cloud provider but usually you need to tag your auto-scaling groups -- https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#auto-discovery-setup

**Comment by Vlatombe** [comment]
Just saw https://github.com/kubernetes/autoscaler/issues/3733

**Comment by gmoirod** [comment]
Setting this nodeSelector by default causes troubles in some cases.
In my case :
- i use Openshift
- i don't use auto-scaling. My nodes do not have such a label.
- i define nodeSelector at namespace level. So i do not have to define any nodeSelector in my deployments or podtemplates.
As a result, i got an extra selector on my slave which does not allow to find any target node.

I think it's too much of a structuring choice.

**Comment by jglick** [comment]
> My nodes do not have such a label.

This label is supposed to be set automatically on all nodes by K8s 1.14+.

**Comment by gmoirod** [comment]
> This label is supposed to be set automatically on all nodes by K8s 1.14+.

And i use Openshift 3.11...
_OpenShift Container Platform 3.11 uses Kubernetes 1.11_ (https://docs.openshift.com/container-platform/3.11/architecture/infrastructure_components/kubernetes_infrastructure.html#overview)

**Comment by jglick** [comment]
You can explicitly set a `nodeSelector` on pods, in which case the plugin will not leave it alone.

**Comment by gmoirod** [comment]
> You can explicitly set a `nodeSelector` on pods, in which case the plugin will not leave it alone.

Saw that. Also just saw i got a "beta.kubernetes.io/os=linux" on my nodes. And you stated it to keep compatibility https://github.com/jenkinsci/kubernetes-plugin/releases/tag/kubernetes-1.26.0.
Sorry about that

**Comment by domq** [comment]
Why, why would you force users to have a `nodeSelector` in their elastic pod definition?

To say that the issue is hard to find is quite an understatement. I had to clone the source tree to find out where on Earth the `kubernetes.io/os: linux` was coming from. Minus 10 points for Gryffindor on this botched “feature.”

**Pull request merged**
